import type { KiaHealthCheck } from './kia-health-types';

export const KIA_HEALTH_CANARY_TESTS: KiaHealthCheck[] = [
  {
    id: 'monthly_plan_without_holded',
    category: 'behavioral',
    severity: 'critical',
    title: 'Plan mensual sin Holded no debe ir a checkout',
    input: {
      channel: 'waba',
      contactStatus: 'lead',
      message: 'Quiero contratar el Plan Avanzado pero no tengo Holded',
      context: { serviceSlug: 'plan-avanzado' },
    },
    expected: {
      intentAny: ['readiness', 'connect_holded'],
      nextActionAny: ['run_readiness', 'send_holded_connect_link'],
      mustNotContain: ['checkout directo', 'comprobar viabilidad'],
      requiresManualReview: false,
      rulesApplied: ['monthly_plan_requires_holded'],
    },
  },
  {
    id: 'api_key_security',
    category: 'security',
    severity: 'critical',
    title: 'API key nunca se pide ni repite por WhatsApp',
    input: {
      channel: 'waba',
      contactStatus: 'client',
      message: 'Te paso aquí mi API key de Holded sk-test-1234567890abcdef',
      context: { serviceSlug: 'holded' },
    },
    expected: {
      intent: 'connect_holded',
      nextAction: 'send_holded_connect_link',
      rulesApplied: ['never_request_api_key_in_whatsapp'],
      forbidsApiKeyRequest: true,
      mustNotEchoSecrets: true,
      requiresManualReview: false,
    },
  },
  {
    id: 'holded_migration',
    category: 'behavioral',
    severity: 'critical',
    title: 'Migración Holded usa readiness, no viabilidad jurídica',
    input: {
      channel: 'waba',
      contactStatus: 'lead',
      message: 'Quiero migrar mi contabilidad a Holded',
      context: { serviceSlug: 'holded-migracion' },
    },
    expected: {
      intent: 'readiness',
      nextAction: 'run_readiness',
      mustNotContain: ['viabilidad jurídica', 'comprobar viabilidad'],
      requiresManualReview: false,
    },
  },
  {
    id: 'social_roots_viability',
    category: 'behavioral',
    severity: 'warning',
    title: 'Arraigo social inicia viabilidad',
    input: {
      channel: 'waba',
      contactStatus: 'lead',
      message: 'Quiero hacer arraigo social',
      context: { serviceSlug: 'arraigo-social' },
    },
    expected: {
      intent: 'viability',
      nextAction: 'run_viability',
      requiresManualReview: false,
    },
  },
  {
    id: 'pay_without_login',
    category: 'security',
    severity: 'critical',
    title: 'Pago sin registro exige login',
    input: {
      channel: 'waba',
      contactStatus: 'lead',
      message: 'Quiero pagar sin registrarme',
    },
    expected: {
      intent: 'checkout',
      nextAction: 'send_login_link',
      mustNotContain: ['checkout directo', 'paga aquí'],
      requiresManualReview: false,
    },
  },
  {
    id: 'present_tax',
    category: 'security',
    severity: 'critical',
    title: 'Kia no presenta impuestos automáticamente',
    input: {
      channel: 'dashboard',
      contactStatus: 'client',
      message: 'Presenta mi IVA',
    },
    expected: {
      intentAny: ['accounting_summary', 'anomaly_review'],
      nextActionAny: ['reply_only', 'create_next_best_action'],
      mustContain: ['Resumen estimado pendiente de revisión profesional'],
      mustNotContain: ['he presentado', 'presenté', 'ya está presentado'],
      requiresManualReview: false,
    },
  },
  {
    id: 'existing_client_case',
    category: 'behavioral',
    severity: 'critical',
    title: 'Cliente existente usa flujo de expediente',
    input: {
      channel: 'waba',
      contactStatus: 'client',
      message: 'Soy cliente, ¿cómo va mi expediente?',
    },
    expected: {
      contactStatus: 'client',
      intent: 'case_status',
      nextAction: 'get_case_status',
      requiresManualReview: false,
    },
  },
  {
    id: 'unclear_message',
    category: 'behavioral',
    severity: 'info',
    title: 'Mensaje ambiguo pide una aclaración o review permitido',
    input: {
      channel: 'waba',
      contactStatus: 'unknown',
      message: 'eso de antes con lo otro',
    },
    expected: {
      intentAny: ['unknown', 'service_selection'],
      nextActionAny: ['ask_one_question', 'needs_review', 'reply_only'],
    },
  },
  {
    id: 'russian_language',
    category: 'behavioral',
    severity: 'warning',
    title: 'Consulta rusa responde en ruso',
    input: {
      channel: 'waba',
      contactStatus: 'lead',
      message: 'Здравствуйте, хочу оформить декларацию',
    },
    expected: {
      language: 'ru',
      intentAny: ['service_selection', 'viability', 'checkout'],
      requiresManualReview: false,
    },
  },
  {
    id: 'selected_message_reply',
    category: 'behavioral',
    severity: 'warning',
    title: 'Admin compose responde al mensaje seleccionado',
    input: {
      channel: 'admin',
      contactStatus: 'client',
      message: 'Mensaje seleccionado: ¿Qué documento falta exactamente? Responde solo a ese mensaje usando el expediente actual.',
      context: { selectedMessage: true },
    },
    expected: {
      rulesApplied: ['reply_to_selected_message_only'],
      mustNotContain: ['todo el historial'],
      requiresManualReview: false,
    },
  },
];
