-- Candidate current-schema baseline for issue #143.
-- Local constraints 001-100 of 338 (CHECK / PRIMARY KEY / UNIQUE).
-- These must be applied before any foreign keys during a fresh bootstrap.

alter table public.academy_enrollments add constraint academy_enrollments_certification_status_check CHECK (certification_status = ANY (ARRAY['none'::text, 'requested'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'paid'::text]));
alter table public.academy_enrollments add constraint academy_enrollments_pkey PRIMARY KEY (id);
alter table public.academy_enrollments add constraint academy_enrollments_status_check CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'completed'::text]));
alter table public.academy_enrollments add constraint academy_enrollments_stripe_payment_id_key UNIQUE (stripe_payment_id);
alter table public.academy_knowledge_status add constraint academy_knowledge_status_pkey PRIMARY KEY (slug);
alter table public.academy_knowledge_status add constraint academy_knowledge_status_status_check CHECK (status = ANY (ARRAY['draft'::text, 'review'::text, 'validated'::text, 'pending_update'::text, 'outdated'::text]));
alter table public.activities add constraint activities_pkey PRIMARY KEY (id);
alter table public.admin_email_folders add constraint admin_email_folders_name_not_blank CHECK (length(btrim(name)) > 0);
alter table public.admin_email_folders add constraint admin_email_folders_pkey PRIMARY KEY (id);
alter table public.admin_email_folders add constraint admin_email_folders_slug_key UNIQUE (slug);
alter table public.admin_email_folders add constraint admin_email_folders_system_consistency CHECK (is_system = true AND system_key IS NOT NULL OR is_system = false AND system_key IS NULL);
alter table public.admin_email_folders add constraint admin_email_folders_system_key_check CHECK (system_key IS NULL OR (system_key = ANY (ARRAY['inbox'::text, 'sent'::text])));
alter table public.admin_email_folders add constraint admin_email_folders_system_key_key UNIQUE (system_key);
alter table public.admin_email_item_state add constraint admin_email_item_state_pkey PRIMARY KEY (id);
alter table public.admin_email_item_state add constraint admin_email_item_state_provider_not_blank CHECK (length(btrim(provider)) > 0);
alter table public.admin_email_item_state add constraint admin_email_item_state_source_key_not_blank CHECK (length(btrim(source_key)) > 0);
alter table public.admin_email_item_state add constraint admin_email_item_state_source_kind_check CHECK (source_kind = ANY (ARRAY['inbox_thread'::text, 'sent_event'::text]));
alter table public.admin_email_item_state add constraint admin_email_item_state_source_unique UNIQUE (source_kind, provider, source_key);
alter table public.admin_users add constraint admin_users_pkey PRIMARY KEY (id);
alter table public.admin_users add constraint admin_users_user_id_key UNIQUE (user_id);
alter table public.aeat_credentials add constraint aeat_credentials_pkey PRIMARY KEY (company_id);
alter table public.ai_logs add constraint ai_logs_pkey PRIMARY KEY (id);
alter table public.appointments add constraint appointments_appointment_type_check CHECK (appointment_type = ANY (ARRAY['consulta_gratuita'::text, 'mentoria'::text, 'asesoramiento'::text]));
alter table public.appointments add constraint appointments_cal_uid_key UNIQUE (cal_uid);
alter table public.appointments add constraint appointments_pkey PRIMARY KEY (id);
alter table public.appointments add constraint appointments_status_check CHECK (status = ANY (ARRAY['pendiente'::text, 'confirmada'::text, 'completada'::text, 'cancelada'::text]));
alter table public.assets_realestate add constraint assets_realestate_pkey PRIMARY KEY (id);
alter table public.assets_vehicles add constraint assets_vehicles_pkey PRIMARY KEY (id);
alter table public.audit_log add constraint audit_log_pkey PRIMARY KEY (id);
alter table public.audit_logs add constraint audit_logs_pkey PRIMARY KEY (id);
alter table public.automation_settings add constraint automation_settings_pkey PRIMARY KEY (key);
alter table public.blog_posts add constraint blog_posts_pkey PRIMARY KEY (id);
alter table public.blog_posts add constraint blog_posts_slug_key UNIQUE (slug);
alter table public.bookings add constraint bookings_pkey PRIMARY KEY (id);
alter table public.campaign_sends add constraint campaign_sends_pkey PRIMARY KEY (id);
alter table public.campaigns add constraint campaigns_pkey PRIMARY KEY (id);
alter table public.case_documents add constraint case_documents_pkey PRIMARY KEY (id);
alter table public.case_documents add constraint case_documents_state_check CHECK (state = ANY (ARRAY['pendiente'::text, 'revisado'::text, 'rechazado'::text]));
alter table public.cases add constraint cases_docs_checklist_is_array CHECK (jsonb_typeof(docs_checklist) = 'array'::text);
alter table public.cases add constraint cases_pkey PRIMARY KEY (id);
alter table public.cases add constraint cases_priority_check CHECK (priority = ANY (ARRAY['baja'::text, 'media'::text, 'alta'::text, 'critica'::text]));
alter table public.cases add constraint cases_state_check CHECK (state = ANY (ARRAY['pendiente_documentacion'::text, 'en_revision'::text, 'en_proceso'::text, 'presentado'::text, 'finalizado'::text]));
alter table public.cases add constraint cases_status_check CHECK (status = ANY (ARRAY['nuevo'::text, 'pendiente_cliente'::text, 'en_revision'::text, 'listo_para_presentar'::text, 'presentado'::text, 'finalizado'::text, 'bloqueado'::text]));
alter table public.categories add constraint categories_pkey PRIMARY KEY (id);
alter table public.categories add constraint categories_slug_key UNIQUE (slug);
alter table public.certificates add constraint certificates_pkey PRIMARY KEY (id);
alter table public.checkout_sessions add constraint checkout_sessions_pkey PRIMARY KEY (id);
alter table public.checkout_sessions add constraint checkout_sessions_stripe_session_id_key UNIQUE (stripe_session_id);
alter table public.client_accounting_records add constraint client_accounting_records_integration_id_record_type_extern_key UNIQUE (integration_id, record_type, external_id);
alter table public.client_accounting_records add constraint client_accounting_records_pkey PRIMARY KEY (id);
alter table public.client_accounting_records add constraint client_accounting_records_record_type_check CHECK (record_type = ANY (ARRAY['sales_invoice'::text, 'purchase_invoice'::text, 'tax'::text, 'bank_movement'::text]));
alter table public.client_integration_secrets add constraint client_integration_secrets_pkey PRIMARY KEY (integration_id);
alter table public.client_integrations add constraint client_integrations_api_version_check CHECK (api_version = ANY (ARRAY['v1'::text, 'v2'::text]));
alter table public.client_integrations add constraint client_integrations_mode_check CHECK (mode = ANY (ARRAY['expert_account'::text, 'client_account'::text]));
alter table public.client_integrations add constraint client_integrations_owner_required CHECK (client_id IS NOT NULL OR company_id IS NOT NULL);
alter table public.client_integrations add constraint client_integrations_pkey PRIMARY KEY (id);
alter table public.client_integrations add constraint client_integrations_status_check CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'failed'::text, 'revoked'::text, 'disabled'::text]));
alter table public.client_integrations add constraint client_integrations_sync_mode_check CHECK (sync_mode = ANY (ARRAY['read_only'::text, 'read_write'::text]));
alter table public.client_portal_invoices add constraint client_portal_invoices_pkey PRIMARY KEY (id);
alter table public.client_service_requests add constraint client_service_requests_pkey PRIMARY KEY (id);
alter table public.companies add constraint companies_pkey PRIMARY KEY (id);
alter table public.companies add constraint companies_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text]));
alter table public.company_data_sources_log add constraint company_data_sources_log_pkey PRIMARY KEY (id);
alter table public.company_data_sources_log add constraint company_data_sources_log_status_check CHECK (status = ANY (ARRAY['ok'::text, 'error'::text, 'empty'::text, 'skipped'::text]));
alter table public.company_data_suggestions add constraint company_data_suggestions_confidence_check CHECK (confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text]));
alter table public.company_data_suggestions add constraint company_data_suggestions_pkey PRIMARY KEY (id);
alter table public.company_fiscal_templates add constraint company_fiscal_templates_dates_check CHECK (effective_to IS NULL OR effective_to >= effective_from);
alter table public.company_fiscal_templates add constraint company_fiscal_templates_pkey PRIMARY KEY (id);
alter table public.company_fiscal_templates add constraint company_fiscal_templates_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text]));
alter table public.company_fiscal_templates add constraint company_fiscal_templates_template_check CHECK (template_code = ANY (ARRAY['303_quarterly'::text, '111_quarterly'::text, '115_quarterly'::text, '130_quarterly'::text, '202_triannual'::text, '200_annual_calendar_year'::text, '390_annual'::text, '347_annual'::text, '190_annual'::text, '180_annual'::text]));
alter table public.company_open_data_query_logs add constraint company_open_data_query_logs_pkey PRIMARY KEY (id);
alter table public.company_open_data_query_logs add constraint company_open_data_query_logs_query_type_check CHECK (query_type = ANY (ARRAY['name'::text, 'tax_id'::text, 'combined'::text]));
alter table public.company_stripe_customers add constraint company_stripe_customers_metadata_check CHECK (jsonb_typeof(metadata) = 'object'::text);
alter table public.company_stripe_customers add constraint company_stripe_customers_pkey PRIMARY KEY (id);
alter table public.company_stripe_customers add constraint company_stripe_customers_status_check CHECK (status = ANY (ARRAY['active'::text, 'historical'::text, 'revoked'::text]));
alter table public.company_stripe_customers add constraint company_stripe_customers_tenant_id_stripe_customer_id_key UNIQUE (tenant_id, stripe_customer_id);
alter table public.connector_audit_logs add constraint connector_audit_logs_pkey PRIMARY KEY (id);
alter table public.connector_instances add constraint connector_instances_pkey PRIMARY KEY (id);
alter table public.connector_instances add constraint uq_connector_instance_client_type UNIQUE (client_id, connector_type);
alter table public.connector_usage_events add constraint connector_usage_events_pkey PRIMARY KEY (id);
alter table public.contact_messages add constraint contact_messages_pkey PRIMARY KEY (id);
alter table public.contact_messages add constraint contact_messages_status_check CHECK (status = ANY (ARRAY['nuevo'::text, 'leído'::text, 'respondido'::text]));
alter table public.contact_requests add constraint contact_requests_estado_check CHECK (estado = ANY (ARRAY['pendiente'::text, 'contactado'::text, 'completado'::text]));
alter table public.contact_requests add constraint contact_requests_pkey PRIMARY KEY (id);
alter table public.contact_requests add constraint contact_requests_tipo_solicitud_check CHECK (tipo_solicitud = ANY (ARRAY['llamada'::text, 'mentoría'::text, 'formación'::text, 'contacto'::text]));
alter table public.contacts add constraint contacts_pkey PRIMARY KEY (id);
alter table public.customers add constraint customers_pkey PRIMARY KEY (id);
alter table public.demo_requests add constraint demo_requests_email_key UNIQUE (email);
alter table public.demo_requests add constraint demo_requests_pkey PRIMARY KEY (id);
alter table public.doc_templates add constraint doc_templates_pkey PRIMARY KEY (id);
alter table public.document_classifications add constraint document_classifications_pkey PRIMARY KEY (id);
alter table public.document_classifications add constraint document_classifications_source_check CHECK (source = ANY (ARRAY['whatsapp'::text, 'email'::text, 'portal'::text, 'drive'::text, 'admin'::text]));
alter table public.document_classifications add constraint document_classifications_status_check CHECK (status = ANY (ARRAY['classified'::text, 'needs_review'::text, 'corrected'::text, 'rejected'::text]));
alter table public.documents add constraint documents_pkey PRIMARY KEY (id);
alter table public.documents add constraint documents_state_check CHECK (state = ANY (ARRAY['pendiente'::text, 'revisado'::text, 'rechazado'::text]));
alter table public.documents add constraint documents_uploaded_by_role_check CHECK (uploaded_by_role = ANY (ARRAY['client'::text, 'admin'::text]));
alter table public.email_attachment_documents add constraint email_attachment_documents_pkey PRIMARY KEY (id);
alter table public.email_attachment_documents add constraint email_attachment_documents_provider_account_email_message_i_key UNIQUE (provider, account_email, message_id, attachment_id);
alter table public.email_attachment_documents add constraint email_attachment_documents_provider_check CHECK (provider = ANY (ARRAY['gmail'::text, 'ms365'::text]));
alter table public.email_attachment_documents add constraint email_attachment_documents_size_bytes_check CHECK (size_bytes >= 0);