-- Candidate current-schema baseline for issue #143.
-- Constraints 001-100, extracted from production catalog on 2026-09-11.

alter table public.academy_enrollments add constraint academy_enrollments_certification_status_check CHECK (certification_status = ANY (ARRAY['none'::text, 'requested'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'paid'::text]));
alter table public.academy_enrollments add constraint academy_enrollments_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.academy_enrollments add constraint academy_enrollments_pkey PRIMARY KEY (id);
alter table public.academy_enrollments add constraint academy_enrollments_status_check CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'completed'::text]));
alter table public.academy_enrollments add constraint academy_enrollments_stripe_payment_id_key UNIQUE (stripe_payment_id);
alter table public.academy_knowledge_status add constraint academy_knowledge_status_pkey PRIMARY KEY (slug);
alter table public.academy_knowledge_status add constraint academy_knowledge_status_status_check CHECK (status = ANY (ARRAY['draft'::text, 'review'::text, 'validated'::text, 'pending_update'::text, 'outdated'::text]));
alter table public.academy_knowledge_status add constraint academy_knowledge_status_validated_by_fkey FOREIGN KEY (validated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.activities add constraint activities_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.activities add constraint activities_pkey PRIMARY KEY (id);
alter table public.admin_email_folders add constraint admin_email_folders_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.admin_email_folders add constraint admin_email_folders_name_not_blank CHECK (length(btrim(name)) > 0);
alter table public.admin_email_folders add constraint admin_email_folders_pkey PRIMARY KEY (id);
alter table public.admin_email_folders add constraint admin_email_folders_slug_key UNIQUE (slug);
alter table public.admin_email_folders add constraint admin_email_folders_system_consistency CHECK (is_system = true AND system_key IS NOT NULL OR is_system = false AND system_key IS NULL);
alter table public.admin_email_folders add constraint admin_email_folders_system_key_check CHECK (system_key IS NULL OR (system_key = ANY (ARRAY['inbox'::text, 'sent'::text])));
alter table public.admin_email_folders add constraint admin_email_folders_system_key_key UNIQUE (system_key);
alter table public.admin_email_item_state add constraint admin_email_item_state_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.admin_email_item_state add constraint admin_email_item_state_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.admin_email_item_state add constraint admin_email_item_state_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.admin_email_item_state add constraint admin_email_item_state_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.admin_email_item_state add constraint admin_email_item_state_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES admin_email_folders(id) ON DELETE SET NULL;
alter table public.admin_email_item_state add constraint admin_email_item_state_pkey PRIMARY KEY (id);
alter table public.admin_email_item_state add constraint admin_email_item_state_provider_not_blank CHECK (length(btrim(provider)) > 0);
alter table public.admin_email_item_state add constraint admin_email_item_state_source_key_not_blank CHECK (length(btrim(source_key)) > 0);
alter table public.admin_email_item_state add constraint admin_email_item_state_source_kind_check CHECK (source_kind = ANY (ARRAY['inbox_thread'::text, 'sent_event'::text]));
alter table public.admin_email_item_state add constraint admin_email_item_state_source_unique UNIQUE (source_kind, provider, source_key);
alter table public.admin_users add constraint admin_users_pkey PRIMARY KEY (id);
alter table public.admin_users add constraint admin_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.admin_users add constraint admin_users_user_id_key UNIQUE (user_id);
alter table public.aeat_credentials add constraint aeat_credentials_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.aeat_credentials add constraint aeat_credentials_pkey PRIMARY KEY (company_id);
alter table public.ai_logs add constraint ai_logs_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.ai_logs add constraint ai_logs_pkey PRIMARY KEY (id);
alter table public.appointments add constraint appointments_appointment_type_check CHECK (appointment_type = ANY (ARRAY['consulta_gratuita'::text, 'mentoria'::text, 'asesoramiento'::text]));
alter table public.appointments add constraint appointments_cal_uid_key UNIQUE (cal_uid);
alter table public.appointments add constraint appointments_pkey PRIMARY KEY (id);
alter table public.appointments add constraint appointments_status_check CHECK (status = ANY (ARRAY['pendiente'::text, 'confirmada'::text, 'completada'::text, 'cancelada'::text]));
alter table public.assets_realestate add constraint assets_realestate_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.assets_realestate add constraint assets_realestate_pkey PRIMARY KEY (id);
alter table public.assets_vehicles add constraint assets_vehicles_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.assets_vehicles add constraint assets_vehicles_pkey PRIMARY KEY (id);
alter table public.audit_log add constraint audit_log_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES users(id);
alter table public.audit_log add constraint audit_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.audit_log add constraint audit_log_pkey PRIMARY KEY (id);
alter table public.audit_logs add constraint audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.audit_logs add constraint audit_logs_pkey PRIMARY KEY (id);
alter table public.automation_settings add constraint automation_settings_pkey PRIMARY KEY (key);
alter table public.blog_posts add constraint blog_posts_pkey PRIMARY KEY (id);
alter table public.blog_posts add constraint blog_posts_slug_key UNIQUE (slug);
alter table public.bookings add constraint bookings_pkey PRIMARY KEY (id);
alter table public.campaign_sends add constraint campaign_sends_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
alter table public.campaign_sends add constraint campaign_sends_pkey PRIMARY KEY (id);
alter table public.campaigns add constraint campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public.campaigns add constraint campaigns_pkey PRIMARY KEY (id);
alter table public.case_documents add constraint case_documents_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_documents add constraint case_documents_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.case_documents add constraint case_documents_pkey PRIMARY KEY (id);
alter table public.case_documents add constraint case_documents_state_check CHECK (state = ANY (ARRAY['pendiente'::text, 'revisado'::text, 'rechazado'::text]));
alter table public.cases add constraint cases_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.cases add constraint cases_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.cases add constraint cases_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.cases add constraint cases_docs_checklist_is_array CHECK (jsonb_typeof(docs_checklist) = 'array'::text);
alter table public.cases add constraint cases_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.cases add constraint cases_pkey PRIMARY KEY (id);
alter table public.cases add constraint cases_priority_check CHECK (priority = ANY (ARRAY['baja'::text, 'media'::text, 'alta'::text, 'critica'::text]));
alter table public.cases add constraint cases_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id);
alter table public.cases add constraint cases_state_check CHECK (state = ANY (ARRAY['pendiente_documentacion'::text, 'en_revision'::text, 'en_proceso'::text, 'presentado'::text, 'finalizado'::text]));
alter table public.cases add constraint cases_status_check CHECK (status = ANY (ARRAY['nuevo'::text, 'pendiente_cliente'::text, 'en_revision'::text, 'listo_para_presentar'::text, 'presentado'::text, 'finalizado'::text, 'bloqueado'::text]));
alter table public.cases add constraint cases_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
alter table public.categories add constraint categories_pkey PRIMARY KEY (id);
alter table public.categories add constraint categories_slug_key UNIQUE (slug);
alter table public.certificates add constraint certificates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.certificates add constraint certificates_pkey PRIMARY KEY (id);
alter table public.checkout_sessions add constraint checkout_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.checkout_sessions add constraint checkout_sessions_pkey PRIMARY KEY (id);
alter table public.checkout_sessions add constraint checkout_sessions_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id);
alter table public.checkout_sessions add constraint checkout_sessions_stripe_session_id_key UNIQUE (stripe_session_id);
alter table public.checkout_sessions add constraint checkout_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_integration_secrets add constraint client_integration_secrets_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES client_integrations(id) ON DELETE CASCADE;
alter table public.client_integration_secrets add constraint client_integration_secrets_pkey PRIMARY KEY (integration_id);
alter table public.client_integrations add constraint client_integrations_api_version_check CHECK (api_version = ANY (ARRAY['v1'::text, 'v2'::text]));
alter table public.client_integrations add constraint client_integrations_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_integrations add constraint client_integrations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.client_integrations add constraint client_integrations_connected_by_fkey FOREIGN KEY (connected_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_integrations add constraint client_integrations_mode_check CHECK (mode = ANY (ARRAY['expert_account'::text, 'client_account'::text]));
alter table public.client_integrations add constraint client_integrations_owner_required CHECK (client_id IS NOT NULL OR company_id IS NOT NULL);
alter table public.client_integrations add constraint client_integrations_pkey PRIMARY KEY (id);
alter table public.client_integrations add constraint client_integrations_status_check CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'failed'::text, 'revoked'::text, 'disabled'::text]));
alter table public.client_integrations add constraint client_integrations_sync_mode_check CHECK (sync_mode = ANY (ARRAY['read_only'::text, 'read_write'::text]));
alter table public.client_portal_invoices add constraint client_portal_invoices_pkey PRIMARY KEY (id);
alter table public.client_service_requests add constraint client_service_requests_pkey PRIMARY KEY (id);
alter table public.client_service_requests add constraint client_service_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.companies add constraint companies_pkey PRIMARY KEY (id);
alter table public.companies add constraint companies_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text]));
alter table public.companies add constraint companies_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
alter table public.companies add constraint companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.company_data_sources_log add constraint company_data_sources_log_pkey PRIMARY KEY (id);
alter table public.company_data_sources_log add constraint company_data_sources_log_status_check CHECK (status = ANY (ARRAY['ok'::text, 'error'::text, 'empty'::text, 'skipped'::text]));
alter table public.company_data_sources_log add constraint company_data_sources_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
