-- Candidate current-schema baseline for issue #143.
-- Constraints 101-200, extracted from production catalog on 2026-09-11.

alter table public.company_data_suggestions add constraint company_data_suggestions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.company_data_suggestions add constraint company_data_suggestions_confidence_check CHECK (confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text]));
alter table public.company_data_suggestions add constraint company_data_suggestions_pkey PRIMARY KEY (id);
alter table public.company_data_suggestions add constraint company_data_suggestions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.company_fiscal_templates add constraint company_fiscal_templates_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.company_fiscal_templates add constraint company_fiscal_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_fiscal_templates add constraint company_fiscal_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.company_fiscal_templates add constraint company_fiscal_templates_dates_check CHECK (effective_to IS NULL OR effective_to >= effective_from);
alter table public.company_fiscal_templates add constraint company_fiscal_templates_pkey PRIMARY KEY (id);
alter table public.company_fiscal_templates add constraint company_fiscal_templates_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text]));
alter table public.company_fiscal_templates add constraint company_fiscal_templates_template_check CHECK (template_code = ANY (ARRAY['303_quarterly'::text, '111_quarterly'::text, '115_quarterly'::text, '130_quarterly'::text, '202_triannual'::text, '200_annual_calendar_year'::text, '390_annual'::text, '347_annual'::text, '190_annual'::text, '180_annual'::text]));
alter table public.company_open_data_query_logs add constraint company_open_data_query_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.company_open_data_query_logs add constraint company_open_data_query_logs_pkey PRIMARY KEY (id);
alter table public.company_open_data_query_logs add constraint company_open_data_query_logs_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.company_open_data_query_logs add constraint company_open_data_query_logs_query_type_check CHECK (query_type = ANY (ARRAY['name'::text, 'tax_id'::text, 'combined'::text]));
alter table public.company_stripe_customers add constraint company_stripe_customers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_stripe_customers add constraint company_stripe_customers_metadata_check CHECK (jsonb_typeof(metadata) = 'object'::text);
alter table public.company_stripe_customers add constraint company_stripe_customers_pkey PRIMARY KEY (id);
alter table public.company_stripe_customers add constraint company_stripe_customers_status_check CHECK (status = ANY (ARRAY['active'::text, 'historical'::text, 'revoked'::text]));
alter table public.company_stripe_customers add constraint company_stripe_customers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.company_stripe_customers add constraint company_stripe_customers_tenant_id_stripe_customer_id_key UNIQUE (tenant_id, stripe_customer_id);
alter table public.connector_audit_logs add constraint connector_audit_logs_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES connector_instances(id) ON DELETE SET NULL;
alter table public.connector_audit_logs add constraint connector_audit_logs_pkey PRIMARY KEY (id);
alter table public.connector_instances add constraint connector_instances_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.connector_instances add constraint connector_instances_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.connector_instances add constraint connector_instances_holded_integration_id_fkey FOREIGN KEY (holded_integration_id) REFERENCES client_integrations(id) ON DELETE SET NULL;
alter table public.connector_instances add constraint connector_instances_pkey PRIMARY KEY (id);
alter table public.connector_instances add constraint uq_connector_instance_client_type UNIQUE (client_id, connector_type);
alter table public.connector_usage_events add constraint connector_usage_events_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES connector_instances(id) ON DELETE CASCADE;
alter table public.connector_usage_events add constraint connector_usage_events_pkey PRIMARY KEY (id);
alter table public.contact_messages add constraint contact_messages_pkey PRIMARY KEY (id);
alter table public.contact_messages add constraint contact_messages_status_check CHECK (status = ANY (ARRAY['nuevo'::text, 'leído'::text, 'respondido'::text]));
alter table public.contact_requests add constraint contact_requests_estado_check CHECK (estado = ANY (ARRAY['pendiente'::text, 'contactado'::text, 'completado'::text]));
alter table public.contact_requests add constraint contact_requests_pkey PRIMARY KEY (id);
alter table public.contact_requests add constraint contact_requests_tipo_solicitud_check CHECK (tipo_solicitud = ANY (ARRAY['llamada'::text, 'mentoría'::text, 'formación'::text, 'contacto'::text]));
alter table public.contacts add constraint contacts_pkey PRIMARY KEY (id);
alter table public.customers add constraint customers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.customers add constraint customers_pkey PRIMARY KEY (id);
alter table public.demo_requests add constraint demo_requests_email_key UNIQUE (email);
alter table public.demo_requests add constraint demo_requests_pkey PRIMARY KEY (id);
alter table public.doc_templates add constraint doc_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.doc_templates add constraint doc_templates_pkey PRIMARY KEY (id);
alter table public.document_classifications add constraint document_classifications_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.document_classifications add constraint document_classifications_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.document_classifications add constraint document_classifications_file_id_fkey FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE;
alter table public.document_classifications add constraint document_classifications_pkey PRIMARY KEY (id);
alter table public.document_classifications add constraint document_classifications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.document_classifications add constraint document_classifications_source_check CHECK (source = ANY (ARRAY['whatsapp'::text, 'email'::text, 'portal'::text, 'drive'::text, 'admin'::text]));
alter table public.document_classifications add constraint document_classifications_status_check CHECK (status = ANY (ARRAY['classified'::text, 'needs_review'::text, 'corrected'::text, 'rejected'::text]));
alter table public.documents add constraint documents_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.documents add constraint documents_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.documents add constraint documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.documents add constraint documents_pkey PRIMARY KEY (id);
alter table public.documents add constraint documents_state_check CHECK (state = ANY (ARRAY['pendiente'::text, 'revisado'::text, 'rechazado'::text]));
alter table public.documents add constraint documents_uploaded_by_role_check CHECK (uploaded_by_role = ANY (ARRAY['client'::text, 'admin'::text]));
alter table public.email_attachment_documents add constraint email_attachment_documents_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.email_attachment_documents add constraint email_attachment_documents_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.email_attachment_documents add constraint email_attachment_documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.email_attachment_documents add constraint email_attachment_documents_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE;
alter table public.email_attachment_documents add constraint email_attachment_documents_pkey PRIMARY KEY (id);
alter table public.email_attachment_documents add constraint email_attachment_documents_provider_account_email_message_i_key UNIQUE (provider, account_email, message_id, attachment_id);
alter table public.email_attachment_documents add constraint email_attachment_documents_provider_check CHECK (provider = ANY (ARRAY['gmail'::text, 'ms365'::text]));
alter table public.email_attachment_documents add constraint email_attachment_documents_size_bytes_check CHECK (size_bytes >= 0);
alter table public.email_events add constraint email_events_pkey PRIMARY KEY (id);
alter table public.email_events add constraint email_events_resent_from_id_fkey FOREIGN KEY (resent_from_id) REFERENCES email_events(id) ON DELETE SET NULL;
alter table public.email_events add constraint email_events_status_check CHECK (status = ANY (ARRAY['sent'::text, 'delivered'::text, 'bounced'::text, 'failed'::text]));
alter table public.email_inbox_cache add constraint email_inbox_cache_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.email_inbox_cache add constraint email_inbox_cache_pkey PRIMARY KEY (thread_id);
alter table public.email_queue add constraint email_queue_pkey PRIMARY KEY (id);
alter table public.email_queue add constraint email_queue_status_check CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'sent'::text, 'failed'::text]));
alter table public.email_threads add constraint email_threads_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.email_threads add constraint email_threads_pkey PRIMARY KEY (id);
alter table public.email_threads add constraint email_threads_thread_id_key UNIQUE (thread_id);
alter table public.establishments add constraint establishments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.establishments add constraint establishments_pkey PRIMARY KEY (id);
alter table public.expert_companies add constraint expert_companies_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.expert_companies add constraint expert_companies_forma_juridica_check CHECK (forma_juridica = ANY (ARRAY['autonomo'::text, 'sl'::text, 'sa'::text, 'slne'::text, 'cb'::text, 'cooperativa'::text, 'fundacion'::text, 'otra'::text]));
alter table public.expert_companies add constraint expert_companies_pkey PRIMARY KEY (id);
alter table public.expert_orders add constraint expert_orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.expert_orders add constraint expert_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES expert_companies(id) ON DELETE SET NULL;
alter table public.expert_orders add constraint expert_orders_pkey PRIMARY KEY (id);
alter table public.expert_orders add constraint expert_orders_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE CASCADE;
alter table public.expert_orders add constraint expert_orders_status_check CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text]));
alter table public.expert_profile_companies add constraint expert_profile_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES expert_companies(id) ON DELETE CASCADE;
alter table public.expert_profile_companies add constraint expert_profile_companies_pkey PRIMARY KEY (profile_id, company_id);
alter table public.expert_profile_companies add constraint expert_profile_companies_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.expert_profile_companies add constraint expert_profile_companies_role_check CHECK (role = ANY (ARRAY['owner'::text, 'member'::text]));
alter table public.express_consultations add constraint express_consultations_pkey PRIMARY KEY (id);
alter table public.external_mappings add constraint external_mappings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.external_mappings add constraint external_mappings_external_entity_not_blank CHECK (length(TRIM(BOTH FROM external_entity)) > 0);
alter table public.external_mappings add constraint external_mappings_external_id_not_blank CHECK (length(TRIM(BOTH FROM external_id)) > 0);
alter table public.external_mappings add constraint external_mappings_local_entity_not_blank CHECK (length(TRIM(BOTH FROM local_entity)) > 0);
alter table public.external_mappings add constraint external_mappings_local_id_not_blank CHECK (length(TRIM(BOTH FROM local_id)) > 0);
alter table public.external_mappings add constraint external_mappings_metadata_is_object CHECK (jsonb_typeof(metadata) = 'object'::text);
alter table public.external_mappings add constraint external_mappings_pkey PRIMARY KEY (id);
alter table public.external_mappings add constraint external_mappings_provider_not_blank CHECK (length(TRIM(BOTH FROM provider)) > 0);
alter table public.faq_submissions add constraint faq_submissions_pkey PRIMARY KEY (id);
alter table public.faqs add constraint faqs_pkey PRIMARY KEY (id);
alter table public.files add constraint files_pkey PRIMARY KEY (id);
alter table public.files add constraint files_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
