-- Candidate current-schema baseline for issue #143.
-- Local constraints 201-300 of 338 (CHECK / PRIMARY KEY / UNIQUE).

alter table public.manual_payments add constraint manual_payments_amount_eur_check CHECK (amount_eur > 0::numeric);
alter table public.manual_payments add constraint manual_payments_pkey PRIMARY KEY (id);
alter table public.memberships add constraint memberships_pkey PRIMARY KEY (user_id, company_id);
alter table public.memberships add constraint memberships_role_check CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'accountant'::text, 'viewer'::text]));
alter table public.messages add constraint messages_pkey PRIMARY KEY (id);
alter table public.messages add constraint messages_sender_role_check CHECK (sender_role = ANY (ARRAY['admin'::text, 'client'::text]));
alter table public.migration_requests add constraint migration_requests_pkey PRIMARY KEY (id);
alter table public.ms365_tokens add constraint ms365_tokens_pkey PRIMARY KEY (id);
alter table public.newsletter_subscribers add constraint newsletter_subscribers_email_key UNIQUE (email);
alter table public.newsletter_subscribers add constraint newsletter_subscribers_pkey PRIMARY KEY (id);
alter table public.next_best_actions add constraint next_best_actions_pkey PRIMARY KEY (id);
alter table public.next_best_actions add constraint next_best_actions_priority_check CHECK (priority = ANY (ARRAY['baja'::text, 'media'::text, 'alta'::text, 'critica'::text]));
alter table public.next_best_actions add constraint next_best_actions_status_check CHECK (status = ANY (ARRAY['open'::text, 'done'::text, 'dismissed'::text]));
alter table public.obligations_calendar add constraint obligations_calendar_pkey PRIMARY KEY (id);
alter table public.obligations_calendar add constraint obligations_calendar_source_check CHECK (source = ANY (ARRAY['manual'::text, 'system'::text]));
alter table public.obligations_calendar add constraint obligations_calendar_status_check CHECK (status = ANY (ARRAY['planned'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text]));
alter table public.orders add constraint orders_pkey PRIMARY KEY (id);
alter table public.orders add constraint orders_source_check CHECK (source = ANY (ARRAY['quote'::text, 'catalog'::text, 'waba'::text, 'academy'::text, 'stripe_import'::text]));
alter table public.orders add constraint orders_status_check CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text, 'paid_invoice_error'::text]));
alter table public.pagos_expert add constraint pagos_expert_payment_intent_id_key UNIQUE (payment_intent_id);
alter table public.pagos_expert add constraint pagos_expert_pkey PRIMARY KEY (id);
alter table public.presupuestos_solicitados add constraint presupuestos_solicitados_pkey PRIMARY KEY (id);
alter table public.presupuestos_solicitados add constraint presupuestos_solicitados_token_aceptacion_key UNIQUE (token_aceptacion);
alter table public.profile_companies add constraint profile_companies_pkey PRIMARY KEY (id);
alter table public.profile_companies add constraint profile_companies_role_check CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text]));
alter table public.profile_companies add constraint profile_companies_unique UNIQUE (profile_id, company_id);
alter table public.profiles add constraint profiles_client_type_allowed CHECK (client_type = ANY (ARRAY['particular'::text, 'autonomo'::text, 'empresa'::text]));
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_role_check CHECK (role = ANY (ARRAY['admin'::text, 'owner'::text, 'client'::text, 'tenant_admin'::text]));
alter table public.profiles add constraint profiles_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text]));
alter table public.proyectos add constraint proyectos_pkey PRIMARY KEY (id);
alter table public.public_support_tickets add constraint public_support_tickets_pkey PRIMARY KEY (id);
alter table public.push_subscriptions add constraint push_subscriptions_endpoint_key UNIQUE (endpoint);
alter table public.push_subscriptions add constraint push_subscriptions_pkey PRIMARY KEY (id);
alter table public.quote_templates add constraint quote_templates_pkey PRIMARY KEY (id);
alter table public.quotes add constraint quotes_docs_checklist_is_array CHECK (jsonb_typeof(docs_checklist) = 'array'::text);
alter table public.quotes add constraint quotes_pkey PRIMARY KEY (id);
alter table public.quotes add constraint quotes_status_check CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'accepted'::text, 'paid'::text, 'expired'::text]));
alter table public.representatives add constraint representatives_pkey PRIMARY KEY (id);
alter table public.resources add constraint resources_category_check CHECK (category = ANY (ARRAY['material_didactico'::text, 'herramientas'::text, 'ebooks'::text, 'manuales'::text, 'videos'::text]));
alter table public.resources add constraint resources_pkey PRIMARY KEY (id);
alter table public.resources add constraint resources_type_check CHECK (type = ANY (ARRAY['gratuito'::text, 'premium'::text, 'exclusivo'::text]));
alter table public.review_requests add constraint review_requests_pkey PRIMARY KEY (id);
alter table public.review_requests add constraint review_requests_status_check CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'declined'::text]));
alter table public.reviews add constraint reviews_pkey PRIMARY KEY (id);
alter table public.reviews add constraint reviews_rating_check CHECK (rating >= 1 AND rating <= 5);
alter table public.role_permissions add constraint role_permissions_pkey PRIMARY KEY (id);
alter table public.saas_leads add constraint saas_leads_consent_check CHECK (consent = true);
alter table public.saas_leads add constraint saas_leads_pkey PRIMARY KEY (id);
alter table public.security_alerts add constraint security_alerts_pkey PRIMARY KEY (id);
alter table public.service_metrics add constraint service_metrics_pkey PRIMARY KEY (id);
alter table public.service_profitability_events add constraint service_profitability_events_estimated_minutes_check CHECK (estimated_minutes > 0);
alter table public.service_profitability_events add constraint service_profitability_events_operator_check CHECK (operator = ANY (ARRAY['kia'::text, 'admin'::text, 'system'::text]));
alter table public.service_profitability_events add constraint service_profitability_events_pkey PRIMARY KEY (id);
alter table public.service_profitability_events add constraint service_profitability_events_source_check CHECK (source = ANY (ARRAY['auto'::text, 'manual'::text]));
alter table public.service_profitability_snapshots add constraint service_profitability_snapshots_margin_status_check CHECK (margin_status = ANY (ARRAY['rentable'::text, 'ajustado'::text, 'no_rentable'::text, 'revisar_precio'::text]));
alter table public.service_profitability_snapshots add constraint service_profitability_snapshots_pkey PRIMARY KEY (id);
alter table public.service_profitability_snapshots add constraint service_profitability_snapshots_scope_check CHECK (scope = ANY (ARRAY['monthly'::text, 'case'::text]));
alter table public.service_readiness_assessments add constraint service_readiness_assessments_pkey PRIMARY KEY (id);
alter table public.service_readiness_assessments add constraint service_readiness_assessments_result_check CHECK (result = ANY (ARRAY['ready'::text, 'not_ready'::text, 'partial'::text]));
alter table public.service_readiness_assessments add constraint service_readiness_assessments_source_check CHECK (source = ANY (ARRAY['web'::text, 'dashboard'::text, 'whatsapp'::text, 'kia'::text]));
alter table public.service_review_responses add constraint service_review_responses_pkey PRIMARY KEY (id);
alter table public.service_reviews add constraint service_reviews_pkey PRIMARY KEY (id);
alter table public.service_reviews add constraint service_reviews_rating_check CHECK (rating >= 1 AND rating <= 5);
alter table public.services add constraint services_pkey PRIMARY KEY (id);
alter table public.services add constraint services_slug_key UNIQUE (slug);
alter table public.servicios_cliente add constraint servicios_cliente_pkey PRIMARY KEY (id);
alter table public.sesiones add constraint sesiones_pkey PRIMARY KEY (id);
alter table public.session_history add constraint session_history_pkey PRIMARY KEY (id);
alter table public.settings add constraint settings_pkey PRIMARY KEY (company_id);
alter table public.shareholders add constraint shareholders_pkey PRIMARY KEY (id);
alter table public.site_config add constraint site_config_key_key UNIQUE (key);
alter table public.site_config add constraint site_config_pkey PRIMARY KEY (id);
alter table public.stripe_accounts add constraint stripe_accounts_email_key UNIQUE (email);
alter table public.stripe_accounts add constraint stripe_accounts_pkey PRIMARY KEY (id);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_customer_id_nonempty CHECK (btrim(stripe_customer_id) <> ''::text);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_invoice_id_nonempty CHECK (btrim(stripe_invoice_id) <> ''::text);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_pkey PRIMARY KEY (id);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_revocation_consistency CHECK (status = 'active'::text AND revoked_at IS NULL AND revoked_by IS NULL AND revocation_reason IS NULL OR status = 'revoked'::text AND revoked_at IS NOT NULL AND revocation_reason IS NOT NULL);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_source_check CHECK (source = ANY (ARRAY['invoice_tax_id'::text, 'manual_review'::text]));
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_status_check CHECK (status = ANY (ARRAY['active'::text, 'revoked'::text]));
alter table public.stripe_processed_events add constraint stripe_processed_events_pkey PRIMARY KEY (event_id);
alter table public.stripe_processed_events add constraint stripe_processed_events_status_check CHECK (status = ANY (ARRAY['processing'::text, 'processed'::text]));
alter table public.subscribers add constraint subscribers_email_key UNIQUE (email);
alter table public.subscribers add constraint subscribers_pkey PRIMARY KEY (id);
alter table public.subscription_checkout_claims add constraint subscription_checkout_claims_pkey PRIMARY KEY (id);
alter table public.subscription_checkout_claims add constraint subscription_checkout_claims_state_check CHECK (state = ANY (ARRAY['claimed'::text, 'open'::text, 'expired'::text, 'manual_review'::text]));
alter table public.subscription_entitlements add constraint subscription_entitlements_benefit_value_check CHECK (benefit_value IS NULL OR benefit_value >= 0::numeric);
alter table public.subscription_entitlements add constraint subscription_entitlements_coverage_scope_check CHECK (coverage_scope IS NULL OR (coverage_scope = ANY (ARRAY['recurring_management'::text, 'subscription_fee'::text, 'custom'::text])));
alter table public.subscription_entitlements add constraint subscription_entitlements_pkey PRIMARY KEY (id);
alter table public.subscription_trials add constraint subscription_trials_pkey PRIMARY KEY (id);
alter table public.subscription_trials add constraint subscription_trials_started_from_check CHECK (started_from = ANY (ARRAY['dashboard'::text, 'waba'::text, 'public_page'::text, 'admin'::text]));
alter table public.subscription_trials add constraint subscription_trials_status_check CHECK (status = ANY (ARRAY['trialing'::text, 'converted'::text, 'canceled'::text, 'expired'::text, 'blocked'::text]));
alter table public.subscriptions add constraint subscriptions_pkey PRIMARY KEY (id);
alter table public.subscriptions add constraint subscriptions_status_check CHECK (status = ANY (ARRAY['active'::text, 'canceled'::text, 'past_due'::text, 'unpaid'::text, 'trialing'::text]));
alter table public.subscriptions add constraint subscriptions_stripe_subscription_id_key UNIQUE (stripe_subscription_id);
alter table public.subscriptions add constraint subscriptions_trial_status_check CHECK (trial_status = ANY (ARRAY['trialing'::text, 'converted'::text, 'canceled'::text, 'expired'::text]));
alter table public.support_tickets add constraint support_tickets_pkey PRIMARY KEY (id);
alter table public.support_tickets add constraint support_tickets_priority_check CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text]));
alter table public.support_tickets add constraint support_tickets_status_check CHECK (status = ANY (ARRAY['open'::text, 'in-progress'::text, 'closed'::text, 'resolved'::text]));