-- Candidate current-schema baseline for issue #143.
-- Constraints 301-400, extracted from production catalog on 2026-09-11.

alter table public.kia_sessions add constraint kia_sessions_phone_number_key UNIQUE (phone_number);
alter table public.kia_sessions add constraint kia_sessions_pkey PRIMARY KEY (id);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_activity_status_check CHECK (activity_status = ANY (ARRAY['no_activity'::text, 'abandoned'::text, 'paid'::text, 'subscribed'::text]));
alter table public.lead_stripe_customers add constraint lead_stripe_customers_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.lead_stripe_customers add constraint lead_stripe_customers_metadata_check CHECK (jsonb_typeof(metadata) = 'object'::text);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_paid_checkouts_check CHECK (paid_checkouts >= 0);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_paid_invoices_check CHECK (paid_invoices >= 0);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_pkey PRIMARY KEY (id);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_succeeded_payment_intents_check CHECK (succeeded_payment_intents >= 0);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_successful_charges_check CHECK (successful_charges >= 0);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_tenant_id_stripe_customer_id_key UNIQUE (tenant_id, stripe_customer_id);
alter table public.leads add constraint leads_lifecycle_stage_check CHECK (lifecycle_stage = ANY (ARRAY['lead'::text, 'prospect'::text, 'customer'::text, 'former_customer'::text]));
alter table public.leads add constraint leads_marketing_status_check CHECK (marketing_status = ANY (ARRAY['unknown'::text, 'consented'::text, 'unsubscribed'::text, 'blocked'::text]));
alter table public.leads add constraint leads_metadata_check CHECK (jsonb_typeof(metadata) = 'object'::text);
alter table public.leads add constraint leads_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id);
alter table public.leads add constraint leads_pkey PRIMARY KEY (id);
alter table public.leads add constraint leads_state_check CHECK (state = ANY (ARRAY['new'::text, 'contacted'::text, 'quoted'::text, 'converted'::text]));
alter table public.leads add constraint leads_stripe_activity_check CHECK (stripe_activity = ANY (ARRAY['no_activity'::text, 'abandoned'::text, 'paid'::text, 'subscribed'::text]));
alter table public.leads add constraint leads_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.manual_payments add constraint manual_payments_amount_eur_check CHECK (amount_eur > 0::numeric);
alter table public.manual_payments add constraint manual_payments_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.manual_payments add constraint manual_payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.manual_payments add constraint manual_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public.manual_payments add constraint manual_payments_pkey PRIMARY KEY (id);
alter table public.memberships add constraint memberships_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.memberships add constraint memberships_pkey PRIMARY KEY (user_id, company_id);
alter table public.memberships add constraint memberships_role_check CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'accountant'::text, 'viewer'::text]));
alter table public.memberships add constraint memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_pkey PRIMARY KEY (id);
alter table public.messages add constraint messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id);
alter table public.messages add constraint messages_sender_role_check CHECK (sender_role = ANY (ARRAY['admin'::text, 'client'::text]));
alter table public.migration_requests add constraint migration_requests_pkey PRIMARY KEY (id);
alter table public.ms365_tokens add constraint ms365_tokens_pkey PRIMARY KEY (id);
alter table public.newsletter_subscribers add constraint newsletter_subscribers_email_key UNIQUE (email);
alter table public.newsletter_subscribers add constraint newsletter_subscribers_pkey PRIMARY KEY (id);
alter table public.next_best_actions add constraint next_best_actions_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.next_best_actions add constraint next_best_actions_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.next_best_actions add constraint next_best_actions_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.next_best_actions add constraint next_best_actions_pkey PRIMARY KEY (id);
alter table public.next_best_actions add constraint next_best_actions_priority_check CHECK (priority = ANY (ARRAY['baja'::text, 'media'::text, 'alta'::text, 'critica'::text]));
alter table public.next_best_actions add constraint next_best_actions_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.next_best_actions add constraint next_best_actions_status_check CHECK (status = ANY (ARRAY['open'::text, 'done'::text, 'dismissed'::text]));
alter table public.obligations_calendar add constraint obligations_calendar_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.obligations_calendar add constraint obligations_calendar_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.obligations_calendar add constraint obligations_calendar_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.obligations_calendar add constraint obligations_calendar_pkey PRIMARY KEY (id);
alter table public.obligations_calendar add constraint obligations_calendar_source_check CHECK (source = ANY (ARRAY['manual'::text, 'system'::text]));
alter table public.obligations_calendar add constraint obligations_calendar_status_check CHECK (status = ANY (ARRAY['planned'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text]));
alter table public.obligations_calendar add constraint obligations_calendar_task_id_fkey FOREIGN KEY (task_id) REFERENCES internal_tasks(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_pkey PRIMARY KEY (id);
alter table public.orders add constraint orders_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_source_check CHECK (source = ANY (ARRAY['quote'::text, 'catalog'::text, 'waba'::text, 'academy'::text, 'stripe_import'::text]));
alter table public.orders add constraint orders_status_check CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text, 'paid_invoice_error'::text]));
alter table public.orders add constraint orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.pagos_expert add constraint pagos_expert_payment_intent_id_key UNIQUE (payment_intent_id);
alter table public.pagos_expert add constraint pagos_expert_pkey PRIMARY KEY (id);
alter table public.pagos_expert add constraint pagos_expert_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.presupuestos_solicitados add constraint presupuestos_solicitados_pkey PRIMARY KEY (id);
alter table public.presupuestos_solicitados add constraint presupuestos_solicitados_token_aceptacion_key UNIQUE (token_aceptacion);
alter table public.profile_companies add constraint profile_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.profile_companies add constraint profile_companies_pkey PRIMARY KEY (id);
alter table public.profile_companies add constraint profile_companies_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profile_companies add constraint profile_companies_role_check CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text]));
alter table public.profile_companies add constraint profile_companies_unique UNIQUE (profile_id, company_id);
alter table public.profiles add constraint profiles_active_company_id_fkey FOREIGN KEY (active_company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.profiles add constraint profiles_client_type_allowed CHECK (client_type = ANY (ARRAY['particular'::text, 'autonomo'::text, 'empresa'::text]));
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_role_check CHECK (role = ANY (ARRAY['admin'::text, 'owner'::text, 'client'::text, 'tenant_admin'::text]));
alter table public.profiles add constraint profiles_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text]));
alter table public.profiles add constraint profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
alter table public.proyectos add constraint proyectos_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.proyectos add constraint proyectos_pkey PRIMARY KEY (id);
alter table public.proyectos add constraint proyectos_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.public_support_tickets add constraint public_support_tickets_pkey PRIMARY KEY (id);
alter table public.push_subscriptions add constraint push_subscriptions_endpoint_key UNIQUE (endpoint);
alter table public.push_subscriptions add constraint push_subscriptions_pkey PRIMARY KEY (id);
alter table public.push_subscriptions add constraint push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.quote_templates add constraint quote_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.quote_templates add constraint quote_templates_pkey PRIMARY KEY (id);
alter table public.quotes add constraint quotes_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.quotes add constraint quotes_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.quotes add constraint quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public.quotes add constraint quotes_docs_checklist_is_array CHECK (jsonb_typeof(docs_checklist) = 'array'::text);
alter table public.quotes add constraint quotes_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.quotes add constraint quotes_pkey PRIMARY KEY (id);
alter table public.quotes add constraint quotes_status_check CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'accepted'::text, 'paid'::text, 'expired'::text]));
alter table public.quotes add constraint quotes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
alter table public.representatives add constraint representatives_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.representatives add constraint representatives_pkey PRIMARY KEY (id);
alter table public.resources add constraint resources_category_check CHECK (category = ANY (ARRAY['material_didactico'::text, 'herramientas'::text, 'ebooks'::text, 'manuales'::text, 'videos'::text]));
alter table public.resources add constraint resources_pkey PRIMARY KEY (id);
alter table public.resources add constraint resources_type_check CHECK (type = ANY (ARRAY['gratuito'::text, 'premium'::text, 'exclusivo'::text]));
alter table public.review_requests add constraint review_requests_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
