-- Candidate current-schema baseline for issue #143.
-- Constraints 401-500, extracted from production catalog on 2026-09-11.

alter table public.review_requests add constraint review_requests_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.review_requests add constraint review_requests_pkey PRIMARY KEY (id);
alter table public.review_requests add constraint review_requests_status_check CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'declined'::text]));
alter table public.reviews add constraint reviews_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.reviews add constraint reviews_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.reviews add constraint reviews_pkey PRIMARY KEY (id);
alter table public.reviews add constraint reviews_rating_check CHECK (rating >= 1 AND rating <= 5);
alter table public.role_permissions add constraint role_permissions_pkey PRIMARY KEY (id);
alter table public.role_permissions add constraint role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES user_roles(id) ON DELETE CASCADE;
alter table public.saas_leads add constraint saas_leads_consent_check CHECK (consent = true);
alter table public.saas_leads add constraint saas_leads_pkey PRIMARY KEY (id);
alter table public.security_alerts add constraint security_alerts_pkey PRIMARY KEY (id);
alter table public.service_metrics add constraint service_metrics_pkey PRIMARY KEY (id);
alter table public.service_metrics add constraint service_metrics_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE;
alter table public.service_profitability_events add constraint service_profitability_events_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.service_profitability_events add constraint service_profitability_events_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.service_profitability_events add constraint service_profitability_events_estimated_minutes_check CHECK (estimated_minutes > 0);
alter table public.service_profitability_events add constraint service_profitability_events_operator_check CHECK (operator = ANY (ARRAY['kia'::text, 'admin'::text, 'system'::text]));
alter table public.service_profitability_events add constraint service_profitability_events_pkey PRIMARY KEY (id);
alter table public.service_profitability_events add constraint service_profitability_events_source_check CHECK (source = ANY (ARRAY['auto'::text, 'manual'::text]));
alter table public.service_profitability_snapshots add constraint service_profitability_snapshots_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.service_profitability_snapshots add constraint service_profitability_snapshots_margin_status_check CHECK (margin_status = ANY (ARRAY['rentable'::text, 'ajustado'::text, 'no_rentable'::text, 'revisar_precio'::text]));
alter table public.service_profitability_snapshots add constraint service_profitability_snapshots_pkey PRIMARY KEY (id);
alter table public.service_profitability_snapshots add constraint service_profitability_snapshots_scope_check CHECK (scope = ANY (ARRAY['monthly'::text, 'case'::text]));
alter table public.service_readiness_assessments add constraint service_readiness_assessments_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.service_readiness_assessments add constraint service_readiness_assessments_pkey PRIMARY KEY (id);
alter table public.service_readiness_assessments add constraint service_readiness_assessments_result_check CHECK (result = ANY (ARRAY['ready'::text, 'not_ready'::text, 'partial'::text]));
alter table public.service_readiness_assessments add constraint service_readiness_assessments_source_check CHECK (source = ANY (ARRAY['web'::text, 'dashboard'::text, 'whatsapp'::text, 'kia'::text]));
alter table public.service_readiness_assessments add constraint service_readiness_assessments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.service_review_responses add constraint service_review_responses_pkey PRIMARY KEY (id);
alter table public.service_review_responses add constraint service_review_responses_review_id_fkey FOREIGN KEY (review_id) REFERENCES service_reviews(id) ON DELETE CASCADE;
alter table public.service_reviews add constraint service_reviews_pkey PRIMARY KEY (id);
alter table public.service_reviews add constraint service_reviews_rating_check CHECK (rating >= 1 AND rating <= 5);
alter table public.service_reviews add constraint service_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.services add constraint services_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id);
alter table public.services add constraint services_pkey PRIMARY KEY (id);
alter table public.services add constraint services_slug_key UNIQUE (slug);
alter table public.servicios_cliente add constraint servicios_cliente_pkey PRIMARY KEY (id);
alter table public.sesiones add constraint sesiones_pkey PRIMARY KEY (id);
alter table public.sesiones add constraint sesiones_proyecto_id_fkey FOREIGN KEY (proyecto_id) REFERENCES proyectos(id) ON DELETE SET NULL;
alter table public.sesiones add constraint sesiones_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.session_history add constraint session_history_pkey PRIMARY KEY (id);
alter table public.session_history add constraint session_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.settings add constraint settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.settings add constraint settings_pkey PRIMARY KEY (company_id);
alter table public.shareholders add constraint shareholders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.shareholders add constraint shareholders_pkey PRIMARY KEY (id);
alter table public.site_config add constraint site_config_key_key UNIQUE (key);
alter table public.site_config add constraint site_config_pkey PRIMARY KEY (id);
alter table public.stripe_accounts add constraint stripe_accounts_email_key UNIQUE (email);
alter table public.stripe_accounts add constraint stripe_accounts_pkey PRIMARY KEY (id);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_customer_id_nonempty CHECK (btrim(stripe_customer_id) <> ''::text);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_invoice_id_nonempty CHECK (btrim(stripe_invoice_id) <> ''::text);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_pkey PRIMARY KEY (id);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_revocation_consistency CHECK (status = 'active'::text AND revoked_at IS NULL AND revoked_by IS NULL AND revocation_reason IS NULL OR status = 'revoked'::text AND revoked_at IS NOT NULL AND revocation_reason IS NOT NULL);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_source_check CHECK (source = ANY (ARRAY['invoice_tax_id'::text, 'manual_review'::text]));
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_status_check CHECK (status = ANY (ARRAY['active'::text, 'revoked'::text]));
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.stripe_processed_events add constraint stripe_processed_events_pkey PRIMARY KEY (event_id);
alter table public.stripe_processed_events add constraint stripe_processed_events_status_check CHECK (status = ANY (ARRAY['processing'::text, 'processed'::text]));
alter table public.subscribers add constraint subscribers_email_key UNIQUE (email);
alter table public.subscribers add constraint subscribers_pkey PRIMARY KEY (id);
alter table public.subscription_checkout_claims add constraint subscription_checkout_claims_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.subscription_checkout_claims add constraint subscription_checkout_claims_pkey PRIMARY KEY (id);
alter table public.subscription_checkout_claims add constraint subscription_checkout_claims_state_check CHECK (state = ANY (ARRAY['claimed'::text, 'open'::text, 'expired'::text, 'manual_review'::text]));
alter table public.subscription_checkout_claims add constraint subscription_checkout_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.subscription_entitlements add constraint subscription_entitlements_beneficiary_company_id_fkey FOREIGN KEY (beneficiary_company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.subscription_entitlements add constraint subscription_entitlements_benefit_value_check CHECK (benefit_value IS NULL OR benefit_value >= 0::numeric);
alter table public.subscription_entitlements add constraint subscription_entitlements_checkout_session_id_fkey FOREIGN KEY (checkout_session_id) REFERENCES checkout_sessions(id) ON DELETE SET NULL;
alter table public.subscription_entitlements add constraint subscription_entitlements_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.subscription_entitlements add constraint subscription_entitlements_coverage_scope_check CHECK (coverage_scope IS NULL OR (coverage_scope = ANY (ARRAY['recurring_management'::text, 'subscription_fee'::text, 'custom'::text])));
alter table public.subscription_entitlements add constraint subscription_entitlements_pkey PRIMARY KEY (id);
alter table public.subscription_entitlements add constraint subscription_entitlements_primary_company_id_fkey FOREIGN KEY (primary_company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.subscription_entitlements add constraint subscription_entitlements_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL;
alter table public.subscription_trials add constraint subscription_trials_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.subscription_trials add constraint subscription_trials_company_id_fkey FOREIGN KEY (company_id) REFERENCES profile_companies(id) ON DELETE SET NULL;
alter table public.subscription_trials add constraint subscription_trials_pkey PRIMARY KEY (id);
alter table public.subscription_trials add constraint subscription_trials_started_from_check CHECK (started_from = ANY (ARRAY['dashboard'::text, 'waba'::text, 'public_page'::text, 'admin'::text]));
alter table public.subscription_trials add constraint subscription_trials_status_check CHECK (status = ANY (ARRAY['trialing'::text, 'converted'::text, 'canceled'::text, 'expired'::text, 'blocked'::text]));
alter table public.subscriptions add constraint subscriptions_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.subscriptions add constraint subscriptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT;
alter table public.subscriptions add constraint subscriptions_pkey PRIMARY KEY (id);
alter table public.subscriptions add constraint subscriptions_status_check CHECK (status = ANY (ARRAY['active'::text, 'canceled'::text, 'past_due'::text, 'unpaid'::text, 'trialing'::text]));
alter table public.subscriptions add constraint subscriptions_stripe_subscription_id_key UNIQUE (stripe_subscription_id);
alter table public.subscriptions add constraint subscriptions_trial_status_check CHECK (trial_status = ANY (ARRAY['trialing'::text, 'converted'::text, 'canceled'::text, 'expired'::text]));
alter table public.support_tickets add constraint support_tickets_pkey PRIMARY KEY (id);
alter table public.support_tickets add constraint support_tickets_priority_check CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text]));
alter table public.support_tickets add constraint support_tickets_status_check CHECK (status = ANY (ARRAY['open'::text, 'in-progress'::text, 'closed'::text, 'resolved'::text]));
alter table public.support_tickets add constraint support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.system_kv add constraint system_kv_pkey PRIMARY KEY (key);
alter table public.tenant_integration_secrets add constraint tenant_integration_secrets_pkey PRIMARY KEY (id);
alter table public.tenant_integration_secrets add constraint tenant_integration_secrets_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
alter table public.tenant_integration_secrets add constraint tenant_integration_secrets_tenant_id_integration_key UNIQUE (tenant_id, integration);
alter table public.tenants add constraint tenants_pkey PRIMARY KEY (id);
alter table public.tenants add constraint tenants_plan_check CHECK (plan = ANY (ARRAY['starter'::text, 'pro'::text, 'enterprise'::text]));
alter table public.tenants add constraint tenants_slug_key UNIQUE (slug);
alter table public.training_orders add constraint training_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
