-- Candidate current-schema baseline for issue #143.
-- Foreign keys 101-200 of 220. Apply only after all local PK/UNIQUE/CHECK constraints.

alter table public.kia_auditor_reviews add constraint kia_auditor_reviews_decision_log_id_fkey FOREIGN KEY (decision_log_id) REFERENCES kia_decision_logs(id) ON DELETE SET NULL;
alter table public.kia_auditor_reviews add constraint kia_auditor_reviews_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.kia_auditor_rule_results add constraint kia_auditor_rule_results_review_id_fkey FOREIGN KEY (review_id) REFERENCES kia_auditor_reviews(id) ON DELETE CASCADE;
alter table public.kia_behavior_anomalies add constraint kia_behavior_anomalies_related_decision_log_id_fkey FOREIGN KEY (related_decision_log_id) REFERENCES kia_decision_logs(id) ON DELETE SET NULL;
alter table public.kia_behavior_anomalies add constraint kia_behavior_anomalies_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kia_cart_items add constraint kia_cart_items_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kia_cart_items add constraint kia_cart_items_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.kia_decision_logs add constraint kia_decision_logs_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kia_decision_logs add constraint kia_decision_logs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.kia_feedback add constraint kia_feedback_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kia_feedback add constraint kia_feedback_decision_log_id_fkey FOREIGN KEY (decision_log_id) REFERENCES kia_decision_logs(id) ON DELETE SET NULL;
alter table public.kia_feedback add constraint kia_feedback_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.kia_financial_reports add constraint kia_financial_reports_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.kia_health_check_results add constraint kia_health_check_results_decision_log_id_fkey FOREIGN KEY (decision_log_id) REFERENCES kia_decision_logs(id) ON DELETE SET NULL;
alter table public.kia_health_check_results add constraint kia_health_check_results_run_id_fkey FOREIGN KEY (run_id) REFERENCES kia_health_runs(id) ON DELETE CASCADE;
alter table public.kia_health_runs add constraint kia_health_runs_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kia_memories add constraint kia_memories_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.kia_memories add constraint kia_memories_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.kia_reports add constraint kia_reports_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kia_reports add constraint kia_reports_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.kia_sessions add constraint kia_sessions_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.lead_stripe_customers add constraint lead_stripe_customers_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.lead_stripe_customers add constraint lead_stripe_customers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.leads add constraint leads_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id);
alter table public.leads add constraint leads_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.manual_payments add constraint manual_payments_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.manual_payments add constraint manual_payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.manual_payments add constraint manual_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public.memberships add constraint memberships_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.memberships add constraint memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id);
alter table public.next_best_actions add constraint next_best_actions_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.next_best_actions add constraint next_best_actions_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.next_best_actions add constraint next_best_actions_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.next_best_actions add constraint next_best_actions_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.obligations_calendar add constraint obligations_calendar_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.obligations_calendar add constraint obligations_calendar_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.obligations_calendar add constraint obligations_calendar_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.obligations_calendar add constraint obligations_calendar_task_id_fkey FOREIGN KEY (task_id) REFERENCES internal_tasks(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.pagos_expert add constraint pagos_expert_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.profile_companies add constraint profile_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.profile_companies add constraint profile_companies_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_active_company_id_fkey FOREIGN KEY (active_company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
alter table public.proyectos add constraint proyectos_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.proyectos add constraint proyectos_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.push_subscriptions add constraint push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.quote_templates add constraint quote_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.quotes add constraint quotes_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.quotes add constraint quotes_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.quotes add constraint quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public.quotes add constraint quotes_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.quotes add constraint quotes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
alter table public.representatives add constraint representatives_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.review_requests add constraint review_requests_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.review_requests add constraint review_requests_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.reviews add constraint reviews_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.reviews add constraint reviews_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.role_permissions add constraint role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES user_roles(id) ON DELETE CASCADE;
alter table public.service_metrics add constraint service_metrics_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE;
alter table public.service_profitability_events add constraint service_profitability_events_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.service_profitability_events add constraint service_profitability_events_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.service_profitability_snapshots add constraint service_profitability_snapshots_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.service_readiness_assessments add constraint service_readiness_assessments_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.service_readiness_assessments add constraint service_readiness_assessments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.service_review_responses add constraint service_review_responses_review_id_fkey FOREIGN KEY (review_id) REFERENCES service_reviews(id) ON DELETE CASCADE;
alter table public.service_reviews add constraint service_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.services add constraint services_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id);
alter table public.sesiones add constraint sesiones_proyecto_id_fkey FOREIGN KEY (proyecto_id) REFERENCES proyectos(id) ON DELETE SET NULL;
alter table public.sesiones add constraint sesiones_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.session_history add constraint session_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.settings add constraint settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.shareholders add constraint shareholders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.stripe_invoice_company_attributions add constraint stripe_invoice_company_attributions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.subscription_checkout_claims add constraint subscription_checkout_claims_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.subscription_checkout_claims add constraint subscription_checkout_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.subscription_entitlements add constraint subscription_entitlements_beneficiary_company_id_fkey FOREIGN KEY (beneficiary_company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.subscription_entitlements add constraint subscription_entitlements_checkout_session_id_fkey FOREIGN KEY (checkout_session_id) REFERENCES checkout_sessions(id) ON DELETE SET NULL;
alter table public.subscription_entitlements add constraint subscription_entitlements_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.subscription_entitlements add constraint subscription_entitlements_primary_company_id_fkey FOREIGN KEY (primary_company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.subscription_entitlements add constraint subscription_entitlements_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL;
alter table public.subscription_trials add constraint subscription_trials_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.subscription_trials add constraint subscription_trials_company_id_fkey FOREIGN KEY (company_id) REFERENCES profile_companies(id) ON DELETE SET NULL;
alter table public.subscriptions add constraint subscriptions_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.subscriptions add constraint subscriptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT;
alter table public.support_tickets add constraint support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.tenant_integration_secrets add constraint tenant_integration_secrets_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
alter table public.training_orders add constraint training_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.training_orders add constraint training_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);