-- Candidate current-schema baseline for issue #143.
-- Secondary indexes 101-200 at snapshot gate 20260911174615.
-- PK/UNIQUE/EXCLUDE backing indexes are created by the constraint layer.

CREATE INDEX holded_demos_created_at_idx ON public.holded_demos USING btree (created_at DESC);
CREATE INDEX holded_demos_email_idx ON public.holded_demos USING btree (lower(email));
CREATE INDEX holded_demos_status_idx ON public.holded_demos USING btree (status);
CREATE INDEX idx_holded_mcp_connections_email ON public.holded_mcp_connections USING btree (email);
CREATE INDEX idx_holded_mcp_connections_status ON public.holded_mcp_connections USING btree (status);
CREATE INDEX idx_holded_mcp_connections_supabase_user ON public.holded_mcp_connections USING btree (supabase_user_id) WHERE (supabase_user_id IS NOT NULL);
CREATE INDEX idx_holded_mcp_events_created ON public.holded_mcp_events USING btree (created_at DESC);
CREATE INDEX idx_holded_mcp_events_user ON public.holded_mcp_events USING btree (user_id_mcp) WHERE (user_id_mcp IS NOT NULL);
CREATE INDEX holded_sync_jobs_company_idx ON public.holded_sync_jobs USING btree (company_id) WHERE (company_id IS NOT NULL);
CREATE INDEX holded_sync_jobs_integration_idx ON public.holded_sync_jobs USING btree (integration_id);
CREATE INDEX holded_sync_jobs_status_next_run_idx ON public.holded_sync_jobs USING btree (status, next_run_at);
CREATE INDEX integration_sync_events_client_idx ON public.integration_sync_events USING btree (client_id) WHERE (client_id IS NOT NULL);
CREATE INDEX integration_sync_events_company_idx ON public.integration_sync_events USING btree (company_id) WHERE (company_id IS NOT NULL);
CREATE INDEX integration_sync_events_external_idx ON public.integration_sync_events USING btree (external_entity, external_id);
CREATE INDEX integration_sync_events_integration_idx ON public.integration_sync_events USING btree (integration_id) WHERE (integration_id IS NOT NULL);
CREATE INDEX integration_sync_events_local_idx ON public.integration_sync_events USING btree (local_entity, local_id);
CREATE INDEX integration_sync_events_provider_created_idx ON public.integration_sync_events USING btree (provider, created_at DESC);
CREATE INDEX integration_sync_events_status_created_idx ON public.integration_sync_events USING btree (status, created_at DESC);
CREATE INDEX idx_internal_tasks_assigned_to ON public.internal_tasks USING btree (assigned_to);
CREATE INDEX idx_internal_tasks_case_id ON public.internal_tasks USING btree (case_id);
CREATE INDEX idx_internal_tasks_due_date ON public.internal_tasks USING btree (due_date) WHERE (due_date IS NOT NULL);
CREATE INDEX idx_internal_tasks_status ON public.internal_tasks USING btree (status);
CREATE INDEX internal_tasks_company_due_idx ON public.internal_tasks USING btree (company_id, due_date) WHERE (company_id IS NOT NULL);
CREATE UNIQUE INDEX internal_tasks_one_open_checkout_followup_per_client ON public.internal_tasks USING btree (client_id) WHERE ((source = 'system'::text) AND (title = 'Formalizar contratación de suscripción'::text) AND (status = ANY (ARRAY['pendiente'::text, 'en_progreso'::text])));
CREATE UNIQUE INDEX internal_tasks_one_open_subscription_onboarding_per_client ON public.internal_tasks USING btree (client_id) WHERE ((source = 'system'::text) AND (title = 'Completar alta tras suscripción'::text) AND (status = ANY (ARRAY['pendiente'::text, 'en_progreso'::text])));
CREATE INDEX idx_invoices_date ON public.invoices USING btree (date);
CREATE INDEX idx_invoices_status ON public.invoices USING btree (status);
CREATE INDEX idx_invoices_user_id ON public.invoices USING btree (user_id);
CREATE INDEX idx_auditor_reviews_client ON public.kia_auditor_reviews USING btree (client_id);
CREATE INDEX idx_auditor_reviews_created ON public.kia_auditor_reviews USING btree (created_at DESC);
CREATE INDEX idx_auditor_reviews_source ON public.kia_auditor_reviews USING btree (source_type);
CREATE INDEX idx_auditor_reviews_status ON public.kia_auditor_reviews USING btree (overall_status);
CREATE INDEX kia_auditor_reviews_created_at_idx ON public.kia_auditor_reviews USING btree (created_at DESC);
CREATE INDEX kia_auditor_reviews_decision_log_idx ON public.kia_auditor_reviews USING btree (decision_log_id, created_at DESC) WHERE (decision_log_id IS NOT NULL);
CREATE INDEX kia_auditor_reviews_status_idx ON public.kia_auditor_reviews USING btree (overall_status, created_at DESC);
CREATE INDEX idx_auditor_rule_results_review ON public.kia_auditor_rule_results USING btree (review_id);
CREATE INDEX idx_auditor_rule_results_rule_id ON public.kia_auditor_rule_results USING btree (rule_id);
CREATE INDEX idx_auditor_rule_results_status ON public.kia_auditor_rule_results USING btree (status);
CREATE INDEX kia_auditor_rule_results_review_idx ON public.kia_auditor_rule_results USING btree (review_id);
CREATE INDEX kia_auditor_rule_results_rule_status_idx ON public.kia_auditor_rule_results USING btree (rule_id, status, created_at DESC);
CREATE INDEX idx_kia_anomalies_created ON public.kia_behavior_anomalies USING btree (created_at DESC);
CREATE INDEX idx_kia_anomalies_resolved ON public.kia_behavior_anomalies USING btree (resolved);
CREATE INDEX idx_kia_anomalies_severity ON public.kia_behavior_anomalies USING btree (severity);
CREATE INDEX kia_behavior_anomalies_open_idx ON public.kia_behavior_anomalies USING btree (severity, created_at DESC) WHERE (status = 'open'::text);
CREATE INDEX kia_behavior_anomalies_type_idx ON public.kia_behavior_anomalies USING btree (anomaly_type, created_at DESC);
CREATE INDEX kia_cart_items_client_idx ON public.kia_cart_items USING btree (client_id) WHERE (client_id IS NOT NULL);
CREATE INDEX kia_cart_items_expires_idx ON public.kia_cart_items USING btree (expires_at);
CREATE INDEX kia_cart_items_lead_idx ON public.kia_cart_items USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX kia_cart_items_phone_idx ON public.kia_cart_items USING btree (phone_number);
CREATE INDEX idx_kia_decision_logs_channel ON public.kia_decision_logs USING btree (channel);
CREATE INDEX idx_kia_decision_logs_client ON public.kia_decision_logs USING btree (client_id);
CREATE INDEX idx_kia_decision_logs_created ON public.kia_decision_logs USING btree (created_at DESC);
CREATE INDEX idx_kia_decision_logs_lead ON public.kia_decision_logs USING btree (lead_id);
CREATE INDEX idx_kia_decision_logs_task ON public.kia_decision_logs USING btree (task_type);
CREATE INDEX kia_feedback_created_at_idx ON public.kia_feedback USING btree (created_at DESC);
CREATE INDEX kia_feedback_decision_log_id_idx ON public.kia_feedback USING btree (decision_log_id) WHERE (decision_log_id IS NOT NULL);
CREATE INDEX kia_feedback_phone_idx ON public.kia_feedback USING btree (phone);
CREATE INDEX kia_feedback_rating_idx ON public.kia_feedback USING btree (rating);
CREATE INDEX idx_kia_financial_reports_client ON public.kia_financial_reports USING btree (client_id);
CREATE INDEX idx_kia_financial_reports_company ON public.kia_financial_reports USING btree (company_id) WHERE (company_id IS NOT NULL);
CREATE INDEX idx_kia_financial_reports_created ON public.kia_financial_reports USING btree (created_at DESC);
CREATE INDEX idx_kia_health_results_run ON public.kia_health_check_results USING btree (run_id);
CREATE INDEX idx_kia_health_results_status ON public.kia_health_check_results USING btree (status);
CREATE INDEX kia_health_check_results_decision_log_idx ON public.kia_health_check_results USING btree (decision_log_id, created_at DESC) WHERE (decision_log_id IS NOT NULL);
CREATE INDEX idx_kia_health_runs_created ON public.kia_health_runs USING btree (created_at DESC);
CREATE INDEX idx_kia_health_runs_status ON public.kia_health_runs USING btree (status);
CREATE INDEX kia_memories_client_id_idx ON public.kia_memories USING btree (client_id) WHERE (client_id IS NOT NULL);
CREATE INDEX kia_memories_created_at_idx ON public.kia_memories USING btree (created_at DESC);
CREATE INDEX kia_memories_embedding_idx ON public.kia_memories USING ivfflat (embedding vector_cosine_ops) WITH (lists='50');
CREATE INDEX kia_memories_lead_id_idx ON public.kia_memories USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX kia_memories_phone_idx ON public.kia_memories USING btree (phone) WHERE (phone IS NOT NULL);
CREATE INDEX kia_reports_client_idx ON public.kia_reports USING btree (client_id) WHERE (client_id IS NOT NULL);
CREATE INDEX kia_reports_lead_idx ON public.kia_reports USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX kia_reports_phone_idx ON public.kia_reports USING btree (phone_number);
CREATE INDEX kia_reports_service_idx ON public.kia_reports USING btree (service_id);
CREATE INDEX idx_kia_sessions_escalated ON public.kia_sessions USING btree (escalated) WHERE (escalated = true);
CREATE INDEX idx_kia_sessions_flow ON public.kia_sessions USING btree (flow, step);
CREATE INDEX idx_kia_sessions_phone ON public.kia_sessions USING btree (phone_number);
CREATE INDEX lead_stripe_customers_activity_idx ON public.lead_stripe_customers USING btree (activity_status, has_active_subscription);
CREATE INDEX lead_stripe_customers_email_idx ON public.lead_stripe_customers USING btree (lower(stripe_email));
CREATE INDEX lead_stripe_customers_lead_idx ON public.lead_stripe_customers USING btree (lead_id);
CREATE INDEX leads_lifecycle_stage_idx ON public.leads USING btree (lifecycle_stage, stripe_activity);
CREATE INDEX leads_marketing_status_idx ON public.leads USING btree (marketing_status);
CREATE UNIQUE INDEX leads_phone_unique ON public.leads USING btree (phone) WHERE (phone IS NOT NULL);
CREATE UNIQUE INDEX leads_phone_unique_idx ON public.leads USING btree (phone) WHERE (phone IS NOT NULL);
CREATE UNIQUE INDEX leads_source_key_unique_idx ON public.leads USING btree (COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), source, source_key) WHERE (source_key IS NOT NULL);
CREATE INDEX leads_tenant_idx ON public.leads USING btree (tenant_id) WHERE (tenant_id IS NOT NULL);
CREATE INDEX manual_payments_case_idx ON public.manual_payments USING btree (case_id) WHERE (case_id IS NOT NULL);
CREATE INDEX manual_payments_client_idx ON public.manual_payments USING btree (client_id);
CREATE INDEX manual_payments_paid_at_idx ON public.manual_payments USING btree (paid_at DESC);
CREATE INDEX messages_unread_admin_idx ON public.messages USING btree (case_id, read_by_admin) WHERE (read_by_admin = false);
CREATE INDEX messages_unread_client_idx ON public.messages USING btree (case_id, read_by_client) WHERE (read_by_client = false);
CREATE INDEX idx_nba_action_type ON public.next_best_actions USING btree (action_type);
CREATE INDEX idx_nba_case_id ON public.next_best_actions USING btree (case_id);
CREATE INDEX idx_nba_client_id ON public.next_best_actions USING btree (client_id);
CREATE INDEX idx_nba_dedup ON public.next_best_actions USING btree (action_type, status, client_id) WHERE (status = 'open'::text);
CREATE INDEX idx_nba_due_at ON public.next_best_actions USING btree (due_at) WHERE (due_at IS NOT NULL);
CREATE INDEX idx_nba_priority ON public.next_best_actions USING btree (priority);
CREATE INDEX idx_nba_status ON public.next_best_actions USING btree (status);
CREATE INDEX obligations_calendar_client_due_idx ON public.obligations_calendar USING btree (client_id, due_date);
