-- Candidate current-schema baseline for issue #143.
-- Secondary indexes 001-100 at snapshot gate 20260911174615.
-- PK/UNIQUE/EXCLUDE backing indexes are created by the constraint layer.

CREATE INDEX academy_enrollments_client_id_idx ON public.academy_enrollments USING btree (client_id);
CREATE INDEX admin_email_item_state_case_idx ON public.admin_email_item_state USING btree (case_id, updated_at DESC);
CREATE INDEX admin_email_item_state_client_idx ON public.admin_email_item_state USING btree (client_id, updated_at DESC);
CREATE INDEX admin_email_item_state_company_idx ON public.admin_email_item_state USING btree (company_id, updated_at DESC);
CREATE INDEX admin_email_item_state_folder_idx ON public.admin_email_item_state USING btree (folder_id, updated_at DESC);
CREATE INDEX appointments_pdate_idx ON public.appointments USING btree (preferred_date DESC NULLS LAST);
CREATE INDEX appointments_status_idx ON public.appointments USING btree (status);
CREATE INDEX audit_logs_actor_idx ON public.audit_logs USING btree (actor_id);
CREATE INDEX audit_logs_created_at_idx ON public.audit_logs USING btree (created_at DESC);
CREATE INDEX audit_logs_entity_idx ON public.audit_logs USING btree (entity, entity_id);
CREATE INDEX bookings_email_idx ON public.bookings USING btree (email);
CREATE INDEX bookings_status_idx ON public.bookings USING btree (status);
CREATE INDEX campaign_sends_campaign_idx ON public.campaign_sends USING btree (campaign_id);
CREATE INDEX campaign_sends_email_idx ON public.campaign_sends USING btree (recipient_email);
CREATE INDEX campaigns_status_idx ON public.campaigns USING btree (status);
CREATE INDEX cases_company_id_idx ON public.cases USING btree (company_id);
CREATE INDEX cases_due_date_idx ON public.cases USING btree (due_date) WHERE (due_date IS NOT NULL);
CREATE INDEX cases_priority_idx ON public.cases USING btree (priority) WHERE (priority <> 'media'::text);
CREATE INDEX cases_state_idx ON public.cases USING btree (state);
CREATE INDEX cases_status_idx ON public.cases USING btree (status);
CREATE INDEX cases_tenant_id_idx ON public.cases USING btree (tenant_id) WHERE (tenant_id IS NOT NULL);
CREATE INDEX cases_updated_at_idx ON public.cases USING btree (updated_at DESC);
CREATE INDEX idx_cases_assigned_to ON public.cases USING btree (assigned_to);
CREATE INDEX idx_cases_client_id ON public.cases USING btree (client_id);
CREATE INDEX idx_cases_due_date ON public.cases USING btree (due_date) WHERE (due_date IS NOT NULL);
CREATE INDEX idx_cases_status ON public.cases USING btree (status);
CREATE INDEX checkout_sessions_company_id_idx ON public.checkout_sessions USING btree (company_id);
CREATE INDEX checkout_sessions_user_status_idx ON public.checkout_sessions USING btree (user_id, status, created_at DESC);
CREATE INDEX idx_checkout_sessions_service_id ON public.checkout_sessions USING btree (service_id);
CREATE INDEX idx_checkout_sessions_status ON public.checkout_sessions USING btree (status);
CREATE INDEX idx_checkout_sessions_stripe_session_id ON public.checkout_sessions USING btree (stripe_session_id);
CREATE INDEX idx_checkout_sessions_user_id ON public.checkout_sessions USING btree (user_id);
CREATE INDEX client_accounting_records_company_idx ON public.client_accounting_records USING btree (company_id, record_type);
CREATE INDEX client_accounting_records_lookup_idx ON public.client_accounting_records USING btree (integration_id, record_type, record_date DESC);
CREATE INDEX client_integrations_client_idx ON public.client_integrations USING btree (client_id) WHERE (client_id IS NOT NULL);
CREATE INDEX client_integrations_company_idx ON public.client_integrations USING btree (company_id) WHERE (company_id IS NOT NULL);
CREATE INDEX client_integrations_provider_status_idx ON public.client_integrations USING btree (provider, status);
CREATE INDEX idx_client_integrations_consent_at ON public.client_integrations USING btree (consent_at) WHERE (consent_at IS NOT NULL);
CREATE INDEX companies_status_created_idx ON public.companies USING btree (status, created_at DESC);
CREATE UNIQUE INDEX companies_stripe_customer_id_unique ON public.companies USING btree (stripe_customer_id) WHERE (stripe_customer_id IS NOT NULL);
CREATE INDEX companies_tenant_id_idx ON public.companies USING btree (tenant_id) WHERE (tenant_id IS NOT NULL);
CREATE INDEX idx_companies_status ON public.companies USING btree (status);
CREATE INDEX idx_companies_user_id ON public.companies USING btree (user_id);
CREATE INDEX idx_cdsl_created_at ON public.company_data_sources_log USING btree (created_at DESC);
CREATE INDEX idx_cdsl_user_id ON public.company_data_sources_log USING btree (user_id);
CREATE INDEX idx_company_suggestions_company ON public.company_data_suggestions USING btree (company_id) WHERE (company_id IS NOT NULL);
CREATE INDEX idx_company_suggestions_profile ON public.company_data_suggestions USING btree (profile_id, created_at DESC);
CREATE INDEX idx_company_suggestions_source ON public.company_data_suggestions USING btree (source, created_at DESC);
CREATE INDEX company_fiscal_templates_company_idx ON public.company_fiscal_templates USING btree (company_id, status, template_code);
CREATE UNIQUE INDEX company_fiscal_templates_one_active ON public.company_fiscal_templates USING btree (client_id, company_id, template_code) WHERE (status = 'active'::text);
CREATE INDEX idx_company_query_logs_profile ON public.company_open_data_query_logs USING btree (profile_id, created_at DESC);
CREATE INDEX company_stripe_customers_company_idx ON public.company_stripe_customers USING btree (company_id, status);
CREATE UNIQUE INDEX company_stripe_customers_one_primary_active_idx ON public.company_stripe_customers USING btree (company_id) WHERE (is_primary AND (status = 'active'::text));
CREATE INDEX idx_audit_logs_client_id ON public.connector_audit_logs USING btree (client_id, created_at DESC);
CREATE INDEX idx_audit_logs_instance_id ON public.connector_audit_logs USING btree (instance_id, created_at DESC);
CREATE INDEX idx_audit_logs_risk_level ON public.connector_audit_logs USING btree (risk_level, created_at DESC) WHERE (risk_level = ANY (ARRAY['high'::text, 'critical'::text]));
CREATE INDEX idx_connector_instances_client_id ON public.connector_instances USING btree (client_id);
CREATE INDEX idx_connector_instances_status ON public.connector_instances USING btree (status) WHERE (status = 'active'::text);
CREATE INDEX idx_usage_events_client_id ON public.connector_usage_events USING btree (client_id, created_at DESC);
CREATE INDEX idx_usage_events_instance_id ON public.connector_usage_events USING btree (instance_id, created_at DESC);
CREATE INDEX contacts_email_idx ON public.contacts USING btree (email);
CREATE INDEX contacts_status_idx ON public.contacts USING btree (status);
CREATE INDEX idx_doc_class_case_id ON public.document_classifications USING btree (case_id);
CREATE INDEX idx_doc_class_client_id ON public.document_classifications USING btree (client_id);
CREATE INDEX idx_doc_class_detected_type ON public.document_classifications USING btree (detected_type);
CREATE INDEX idx_doc_class_status ON public.document_classifications USING btree (status);
CREATE INDEX documents_case_id_idx ON public.documents USING btree (case_id);
CREATE INDEX documents_client_id_idx ON public.documents USING btree (client_id);
CREATE INDEX idx_documents_company_created ON public.documents USING btree (company_id, created_at DESC);
CREATE INDEX idx_documents_owner ON public.documents USING btree (owner_type, owner_id);
CREATE INDEX email_attachment_documents_case_idx ON public.email_attachment_documents USING btree (case_id, created_at DESC);
CREATE INDEX email_attachment_documents_client_idx ON public.email_attachment_documents USING btree (client_id, created_at DESC);
CREATE INDEX email_attachment_documents_conversation_idx ON public.email_attachment_documents USING btree (provider, account_email, conversation_id) WHERE (conversation_id IS NOT NULL);
CREATE INDEX email_attachment_documents_document_idx ON public.email_attachment_documents USING btree (document_id);
CREATE INDEX email_inbox_cache_date_idx ON public.email_inbox_cache USING btree (date DESC);
CREATE INDEX email_inbox_cache_unread_idx ON public.email_inbox_cache USING btree (unread) WHERE (unread = true);
CREATE INDEX email_queue_pending_idx ON public.email_queue USING btree (scheduled_at) WHERE (status = 'pending'::text);
CREATE INDEX email_queue_status_scheduled_idx ON public.email_queue USING btree (status, scheduled_at) WHERE (status = ANY (ARRAY['pending'::text, 'failed'::text]));
CREATE INDEX idx_email_threads_case ON public.email_threads USING btree (case_id);
CREATE INDEX idx_email_threads_client ON public.email_threads USING btree (client_email);
CREATE INDEX external_mappings_company_idx ON public.external_mappings USING btree (company_id) WHERE (company_id IS NOT NULL);
CREATE INDEX external_mappings_external_idx ON public.external_mappings USING btree (external_entity, external_id);
CREATE UNIQUE INDEX external_mappings_external_unique_idx ON public.external_mappings USING btree (provider, COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), external_entity, external_id);
CREATE INDEX external_mappings_local_idx ON public.external_mappings USING btree (local_entity, local_id);
CREATE UNIQUE INDEX external_mappings_local_unique_idx ON public.external_mappings USING btree (provider, COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), local_entity, local_id, external_entity);
CREATE INDEX external_mappings_provider_idx ON public.external_mappings USING btree (provider, created_at DESC);
CREATE INDEX idx_files_category ON public.files USING btree (category);
CREATE INDEX idx_files_user_id ON public.files USING btree (user_id);
CREATE INDEX fiscal_obligations_status_deadline_idx ON public.fiscal_obligations USING btree (status, deadline);
CREATE INDEX fiscal_obligations_template_idx ON public.fiscal_obligations USING btree (company_id, template_code, year);
CREATE UNIQUE INDEX fiscal_obligations_upsert_key ON public.fiscal_obligations USING btree (user_id, company_id, year, obligation_key) NULLS NOT DISTINCT;
CREATE INDEX fiscal_obligations_user_year_idx ON public.fiscal_obligations USING btree (user_id, year);
CREATE INDEX idx_fiscal_obligations_company_id ON public.fiscal_obligations USING btree (company_id);
CREATE INDEX idx_fiscal_obligations_deadline ON public.fiscal_obligations USING btree (deadline);
CREATE INDEX idx_fiscal_obligations_status ON public.fiscal_obligations USING btree (status);
CREATE INDEX idx_fiscal_obligations_user_id ON public.fiscal_obligations USING btree (user_id);
CREATE INDEX idx_free_trial_requests_created_at ON public.free_trial_requests USING btree (created_at);
CREATE INDEX idx_free_trial_requests_email ON public.free_trial_requests USING btree (email);
CREATE INDEX idx_free_trial_requests_status ON public.free_trial_requests USING btree (status);
CREATE UNIQUE INDEX holded_contact_creation_claims_active_company_uidx ON public.holded_contact_creation_claims USING btree (company_id) WHERE (state = ANY (ARRAY['claimed'::text, 'creating'::text, 'completed'::text, 'manual_review'::text]));
