-- Candidate current-schema baseline for issue #143.
-- Foreign keys 001-100 of 220. Apply only after all local PK/UNIQUE/CHECK constraints.

alter table public.academy_enrollments add constraint academy_enrollments_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.academy_knowledge_status add constraint academy_knowledge_status_validated_by_fkey FOREIGN KEY (validated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.activities add constraint activities_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.admin_email_folders add constraint admin_email_folders_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.admin_email_item_state add constraint admin_email_item_state_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.admin_email_item_state add constraint admin_email_item_state_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.admin_email_item_state add constraint admin_email_item_state_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.admin_email_item_state add constraint admin_email_item_state_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.admin_email_item_state add constraint admin_email_item_state_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES admin_email_folders(id) ON DELETE SET NULL;
alter table public.admin_users add constraint admin_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.aeat_credentials add constraint aeat_credentials_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.ai_logs add constraint ai_logs_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.assets_realestate add constraint assets_realestate_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.assets_vehicles add constraint assets_vehicles_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.audit_log add constraint audit_log_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES users(id);
alter table public.audit_log add constraint audit_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.audit_logs add constraint audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.campaign_sends add constraint campaign_sends_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
alter table public.campaigns add constraint campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public.case_documents add constraint case_documents_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_documents add constraint case_documents_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.cases add constraint cases_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.cases add constraint cases_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.cases add constraint cases_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.cases add constraint cases_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.cases add constraint cases_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id);
alter table public.cases add constraint cases_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
alter table public.certificates add constraint certificates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.checkout_sessions add constraint checkout_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.checkout_sessions add constraint checkout_sessions_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id);
alter table public.checkout_sessions add constraint checkout_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_accounting_records add constraint client_accounting_records_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.client_accounting_records add constraint client_accounting_records_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES client_integrations(id) ON DELETE CASCADE;
alter table public.client_integration_secrets add constraint client_integration_secrets_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES client_integrations(id) ON DELETE CASCADE;
alter table public.client_integrations add constraint client_integrations_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_integrations add constraint client_integrations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.client_integrations add constraint client_integrations_connected_by_fkey FOREIGN KEY (connected_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_service_requests add constraint client_service_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.companies add constraint companies_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
alter table public.companies add constraint companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.company_data_sources_log add constraint company_data_sources_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.company_data_suggestions add constraint company_data_suggestions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.company_data_suggestions add constraint company_data_suggestions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.company_fiscal_templates add constraint company_fiscal_templates_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.company_fiscal_templates add constraint company_fiscal_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_fiscal_templates add constraint company_fiscal_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.company_open_data_query_logs add constraint company_open_data_query_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.company_open_data_query_logs add constraint company_open_data_query_logs_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.company_stripe_customers add constraint company_stripe_customers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_stripe_customers add constraint company_stripe_customers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.connector_audit_logs add constraint connector_audit_logs_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES connector_instances(id) ON DELETE SET NULL;
alter table public.connector_instances add constraint connector_instances_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.connector_instances add constraint connector_instances_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.connector_instances add constraint connector_instances_holded_integration_id_fkey FOREIGN KEY (holded_integration_id) REFERENCES client_integrations(id) ON DELETE SET NULL;
alter table public.connector_usage_events add constraint connector_usage_events_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES connector_instances(id) ON DELETE CASCADE;
alter table public.customers add constraint customers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.doc_templates add constraint doc_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.document_classifications add constraint document_classifications_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.document_classifications add constraint document_classifications_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.document_classifications add constraint document_classifications_file_id_fkey FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE;
alter table public.document_classifications add constraint document_classifications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.documents add constraint documents_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.documents add constraint documents_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.documents add constraint documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.email_attachment_documents add constraint email_attachment_documents_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.email_attachment_documents add constraint email_attachment_documents_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.email_attachment_documents add constraint email_attachment_documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.email_attachment_documents add constraint email_attachment_documents_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE;
alter table public.email_events add constraint email_events_resent_from_id_fkey FOREIGN KEY (resent_from_id) REFERENCES email_events(id) ON DELETE SET NULL;
alter table public.email_inbox_cache add constraint email_inbox_cache_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.email_threads add constraint email_threads_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.establishments add constraint establishments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.expert_companies add constraint expert_companies_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.expert_orders add constraint expert_orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id);
alter table public.expert_orders add constraint expert_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES expert_companies(id) ON DELETE SET NULL;
alter table public.expert_orders add constraint expert_orders_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE CASCADE;
alter table public.expert_profile_companies add constraint expert_profile_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES expert_companies(id) ON DELETE CASCADE;
alter table public.expert_profile_companies add constraint expert_profile_companies_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.external_mappings add constraint external_mappings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.files add constraint files_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.fiscal_obligations add constraint fiscal_obligations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.fiscal_obligations add constraint fiscal_obligations_obligations_calendar_id_fkey FOREIGN KEY (obligations_calendar_id) REFERENCES obligations_calendar(id) ON DELETE SET NULL;
alter table public.fiscal_obligations add constraint fiscal_obligations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.google_tokens add constraint google_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.holded_contact_creation_claims add constraint holded_contact_creation_claims_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.holded_mcp_connections add constraint holded_mcp_connections_supabase_user_id_fkey FOREIGN KEY (supabase_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.holded_sync_jobs add constraint holded_sync_jobs_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.holded_sync_jobs add constraint holded_sync_jobs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.holded_sync_jobs add constraint holded_sync_jobs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES client_integrations(id) ON DELETE CASCADE;
alter table public.integration_sync_events add constraint integration_sync_events_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.integration_sync_events add constraint integration_sync_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.integration_sync_events add constraint integration_sync_events_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES client_integrations(id) ON DELETE SET NULL;
alter table public.internal_tasks add constraint internal_tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.internal_tasks add constraint internal_tasks_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.internal_tasks add constraint internal_tasks_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.internal_tasks add constraint internal_tasks_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.internal_tasks add constraint internal_tasks_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.invoices add constraint invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.kia_auditor_reviews add constraint kia_auditor_reviews_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kia_auditor_reviews add constraint kia_auditor_reviews_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE SET NULL;