-- Candidate current-schema baseline for issue #143.
-- Local constraints 101-200 of 338 (CHECK / PRIMARY KEY / UNIQUE).

alter table public.email_events add constraint email_events_pkey PRIMARY KEY (id);
alter table public.email_events add constraint email_events_status_check CHECK (status = ANY (ARRAY['sent'::text, 'delivered'::text, 'bounced'::text, 'failed'::text]));
alter table public.email_inbox_cache add constraint email_inbox_cache_pkey PRIMARY KEY (thread_id);
alter table public.email_queue add constraint email_queue_pkey PRIMARY KEY (id);
alter table public.email_queue add constraint email_queue_status_check CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'sent'::text, 'failed'::text]));
alter table public.email_threads add constraint email_threads_pkey PRIMARY KEY (id);
alter table public.email_threads add constraint email_threads_thread_id_key UNIQUE (thread_id);
alter table public.establishments add constraint establishments_pkey PRIMARY KEY (id);
alter table public.expert_companies add constraint expert_companies_forma_juridica_check CHECK (forma_juridica = ANY (ARRAY['autonomo'::text, 'sl'::text, 'sa'::text, 'slne'::text, 'cb'::text, 'cooperativa'::text, 'fundacion'::text, 'otra'::text]));
alter table public.expert_companies add constraint expert_companies_pkey PRIMARY KEY (id);
alter table public.expert_orders add constraint expert_orders_pkey PRIMARY KEY (id);
alter table public.expert_orders add constraint expert_orders_status_check CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text]));
alter table public.expert_profile_companies add constraint expert_profile_companies_pkey PRIMARY KEY (profile_id, company_id);
alter table public.expert_profile_companies add constraint expert_profile_companies_role_check CHECK (role = ANY (ARRAY['owner'::text, 'member'::text]));
alter table public.express_consultations add constraint express_consultations_pkey PRIMARY KEY (id);
alter table public.external_mappings add constraint external_mappings_external_entity_not_blank CHECK (length(TRIM(BOTH FROM external_entity)) > 0);
alter table public.external_mappings add constraint external_mappings_external_id_not_blank CHECK (length(TRIM(BOTH FROM external_id)) > 0);
alter table public.external_mappings add constraint external_mappings_local_entity_not_blank CHECK (length(TRIM(BOTH FROM local_entity)) > 0);
alter table public.external_mappings add constraint external_mappings_local_id_not_blank CHECK (length(TRIM(BOTH FROM local_id)) > 0);
alter table public.external_mappings add constraint external_mappings_metadata_is_object CHECK (jsonb_typeof(metadata) = 'object'::text);
alter table public.external_mappings add constraint external_mappings_pkey PRIMARY KEY (id);
alter table public.external_mappings add constraint external_mappings_provider_not_blank CHECK (length(TRIM(BOTH FROM provider)) > 0);
alter table public.faq_submissions add constraint faq_submissions_pkey PRIMARY KEY (id);
alter table public.faqs add constraint faqs_pkey PRIMARY KEY (id);
alter table public.files add constraint files_pkey PRIMARY KEY (id);
alter table public.fiscal_obligations add constraint fiscal_obligations_pkey PRIMARY KEY (id);
alter table public.fiscal_obligations add constraint fiscal_obligations_status_check CHECK (status = ANY (ARRAY['pending'::text, 'submitted'::text, 'exempt'::text, 'skipped'::text]));
alter table public.fiscal_obligations add constraint fiscal_obligations_user_id_company_id_year_obligation_key_key UNIQUE (user_id, company_id, year, obligation_key);
alter table public.free_trial_requests add constraint free_trial_requests_pkey PRIMARY KEY (id);
alter table public.gmail_tokens add constraint gmail_tokens_pkey PRIMARY KEY (id);
alter table public.google_tokens add constraint google_tokens_pkey PRIMARY KEY (user_id);
alter table public.holded_contact_creation_claims add constraint holded_contact_creation_claims_pkey PRIMARY KEY (id);
alter table public.holded_contact_creation_claims add constraint holded_contact_creation_claims_state_check CHECK (state = ANY (ARRAY['claimed'::text, 'creating'::text, 'completed'::text, 'released'::text, 'manual_review'::text]));
alter table public.holded_demos add constraint holded_demos_pkey PRIMARY KEY (id);
alter table public.holded_mcp_connections add constraint holded_mcp_connections_channel_check CHECK (channel = ANY (ARRAY['claude'::text, 'chatgpt'::text, 'mobile'::text, 'dashboard'::text]));
alter table public.holded_mcp_connections add constraint holded_mcp_connections_mcp_user_id_channel_key UNIQUE (mcp_user_id, channel);
alter table public.holded_mcp_connections add constraint holded_mcp_connections_pkey PRIMARY KEY (id);
alter table public.holded_mcp_connections add constraint holded_mcp_connections_status_check CHECK (status = ANY (ARRAY['connected'::text, 'revoked'::text, 'error'::text]));
alter table public.holded_mcp_events add constraint holded_mcp_events_pkey PRIMARY KEY (id);
alter table public.holded_sync_jobs add constraint holded_sync_jobs_period_quarter_check CHECK (period_quarter >= 1 AND period_quarter <= 4);
alter table public.holded_sync_jobs add constraint holded_sync_jobs_pkey PRIMARY KEY (id);
alter table public.holded_sync_jobs add constraint holded_sync_jobs_status_check CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'success'::text, 'failed'::text, 'retrying'::text, 'cancelled'::text]));
alter table public.implementation_projects add constraint implementation_projects_pkey PRIMARY KEY (id);
alter table public.integration_sync_events add constraint integration_sync_events_attempt_count_check CHECK (attempt_count >= 1);
alter table public.integration_sync_events add constraint integration_sync_events_direction_check CHECK (direction = ANY (ARRAY['to_external'::text, 'from_external'::text]));
alter table public.integration_sync_events add constraint integration_sync_events_pkey PRIMARY KEY (id);
alter table public.integration_sync_events add constraint integration_sync_events_status_check CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'skipped'::text, 'retrying'::text]));
alter table public.internal_tasks add constraint internal_tasks_pkey PRIMARY KEY (id);
alter table public.internal_tasks add constraint internal_tasks_priority_check CHECK (priority = ANY (ARRAY['baja'::text, 'media'::text, 'alta'::text, 'critica'::text]));
alter table public.internal_tasks add constraint internal_tasks_source_check CHECK (source = ANY (ARRAY['manual'::text, 'kia'::text, 'system'::text, 'fiscal_calendar'::text, 'document'::text, 'anomaly'::text]));
alter table public.internal_tasks add constraint internal_tasks_status_check CHECK (status = ANY (ARRAY['pendiente'::text, 'en_progreso'::text, 'completada'::text, 'cancelada'::text]));
alter table public.invoice_lines add constraint invoice_lines_pkey PRIMARY KEY (id);
alter table public.invoices add constraint invoices_invoice_number_key UNIQUE (invoice_number);
alter table public.invoices add constraint invoices_pkey PRIMARY KEY (id);
alter table public.invoices add constraint invoices_status_check CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'overdue'::text]));
alter table public.kia_auditor_reviews add constraint kia_auditor_reviews_channel_check CHECK (channel = ANY (ARRAY['waba'::text, 'admin'::text, 'email'::text, 'dashboard'::text, 'document'::text]));
alter table public.kia_auditor_reviews add constraint kia_auditor_reviews_overall_status_check CHECK (overall_status = ANY (ARRAY['pass'::text, 'warning'::text, 'fail'::text]));
alter table public.kia_auditor_reviews add constraint kia_auditor_reviews_pkey PRIMARY KEY (id);
alter table public.kia_auditor_reviews add constraint kia_auditor_reviews_source_type_check CHECK (source_type = ANY (ARRAY['decision_log'::text, 'conversation'::text, 'message'::text, 'health_check'::text, 'manual'::text, 'post_deploy'::text]));
alter table public.kia_auditor_rule_results add constraint kia_auditor_rule_results_category_check CHECK (category = ANY (ARRAY['safety'::text, 'privacy'::text, 'business_flow'::text, 'checkout'::text, 'holded'::text, 'tax'::text, 'accounting'::text, 'language'::text, 'tone'::text, 'consistency'::text, 'tool_use'::text]));
alter table public.kia_auditor_rule_results add constraint kia_auditor_rule_results_pkey PRIMARY KEY (id);
alter table public.kia_auditor_rule_results add constraint kia_auditor_rule_results_severity_check CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text]));
alter table public.kia_auditor_rule_results add constraint kia_auditor_rule_results_status_check CHECK (status = ANY (ARRAY['passed'::text, 'failed'::text, 'warning'::text, 'skipped'::text]));
alter table public.kia_behavior_anomalies add constraint kia_behavior_anomalies_anomaly_type_check CHECK (anomaly_type = ANY (ARRAY['invalid_json'::text, 'wrong_intent'::text, 'wrong_flow'::text, 'forbidden_checkout'::text, 'api_key_leak_risk'::text, 'hallucination_risk'::text, 'wrong_language'::text, 'excessive_needs_review'::text, 'tool_schema_error'::text, 'latency_spike'::text, 'provider_failure'::text, 'unsafe_accounting_action'::text, 'tax_presentation_claim'::text, 'repeated_answer_loop'::text, 'auditor_rule_failure'::text]));
alter table public.kia_behavior_anomalies add constraint kia_behavior_anomalies_pkey PRIMARY KEY (id);
alter table public.kia_behavior_anomalies add constraint kia_behavior_anomalies_severity_check CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text]));
alter table public.kia_behavior_anomalies add constraint kia_behavior_anomalies_source_check CHECK (source = ANY (ARRAY['canary'::text, 'production'::text, 'admin_review'::text, 'eval'::text]));
alter table public.kia_behavior_anomalies add constraint kia_behavior_anomalies_status_check CHECK (status = ANY (ARRAY['open'::text, 'acknowledged'::text, 'fixed'::text, 'ignored'::text]));
alter table public.kia_cart_items add constraint kia_cart_items_pkey PRIMARY KEY (id);
alter table public.kia_decision_logs add constraint kia_decision_logs_pkey PRIMARY KEY (id);
alter table public.kia_feedback add constraint kia_feedback_pkey PRIMARY KEY (id);
alter table public.kia_feedback add constraint kia_feedback_rating_check CHECK (rating = ANY (ARRAY['positive'::text, 'negative'::text]));
alter table public.kia_financial_reports add constraint kia_financial_reports_generated_by_check CHECK (generated_by = ANY (ARRAY['kia'::text, 'admin'::text, 'user'::text]));
alter table public.kia_financial_reports add constraint kia_financial_reports_pkey PRIMARY KEY (id);
alter table public.kia_health_check_results add constraint kia_health_check_results_pkey PRIMARY KEY (id);
alter table public.kia_health_check_results add constraint kia_health_check_results_status_check CHECK (status = ANY (ARRAY['passed'::text, 'failed'::text, 'warning'::text, 'skipped'::text]));
alter table public.kia_health_runs add constraint kia_health_runs_pkey PRIMARY KEY (id);
alter table public.kia_health_runs add constraint kia_health_runs_status_check CHECK (status = ANY (ARRAY['success'::text, 'warning'::text, 'failed'::text]));
alter table public.kia_memories add constraint kia_memories_memory_type_check CHECK (memory_type = ANY (ARRAY['conversation_summary'::text, 'key_fact'::text, 'preference'::text, 'service_interest'::text]));
alter table public.kia_memories add constraint kia_memories_pkey PRIMARY KEY (id);
alter table public.kia_reports add constraint kia_reports_generated_by_check CHECK (generated_by = ANY (ARRAY['kia'::text, 'admin'::text, 'system'::text]));
alter table public.kia_reports add constraint kia_reports_lang_check CHECK (lang = ANY (ARRAY['es'::text, 'ru'::text]));
alter table public.kia_reports add constraint kia_reports_pkey PRIMARY KEY (id);
alter table public.kia_reports add constraint kia_reports_viabilidad_check CHECK (viabilidad = ANY (ARRAY['alta'::text, 'media'::text, 'baja'::text, 'no_viable'::text]));
alter table public.kia_sessions add constraint kia_sessions_phone_number_key UNIQUE (phone_number);
alter table public.kia_sessions add constraint kia_sessions_pkey PRIMARY KEY (id);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_activity_status_check CHECK (activity_status = ANY (ARRAY['no_activity'::text, 'abandoned'::text, 'paid'::text, 'subscribed'::text]));
alter table public.lead_stripe_customers add constraint lead_stripe_customers_metadata_check CHECK (jsonb_typeof(metadata) = 'object'::text);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_paid_checkouts_check CHECK (paid_checkouts >= 0);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_paid_invoices_check CHECK (paid_invoices >= 0);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_pkey PRIMARY KEY (id);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_succeeded_payment_intents_check CHECK (succeeded_payment_intents >= 0);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_successful_charges_check CHECK (successful_charges >= 0);
alter table public.lead_stripe_customers add constraint lead_stripe_customers_tenant_id_stripe_customer_id_key UNIQUE (tenant_id, stripe_customer_id);
alter table public.leads add constraint leads_lifecycle_stage_check CHECK (lifecycle_stage = ANY (ARRAY['lead'::text, 'prospect'::text, 'customer'::text, 'former_customer'::text]));
alter table public.leads add constraint leads_marketing_status_check CHECK (marketing_status = ANY (ARRAY['unknown'::text, 'consented'::text, 'unsubscribed'::text, 'blocked'::text]));
alter table public.leads add constraint leads_metadata_check CHECK (jsonb_typeof(metadata) = 'object'::text);
alter table public.leads add constraint leads_pkey PRIMARY KEY (id);
alter table public.leads add constraint leads_state_check CHECK (state = ANY (ARRAY['new'::text, 'contacted'::text, 'quoted'::text, 'converted'::text]));
alter table public.leads add constraint leads_stripe_activity_check CHECK (stripe_activity = ANY (ARRAY['no_activity'::text, 'abandoned'::text, 'paid'::text, 'subscribed'::text]));