-- Candidate current-schema baseline for issue #143.
-- Secondary indexes 201-283 at snapshot gate 20260911174615.
-- PK/UNIQUE/EXCLUDE backing indexes are created by the constraint layer.

CREATE INDEX obligations_calendar_company_due_idx ON public.obligations_calendar USING btree (company_id, due_date);
CREATE UNIQUE INDEX obligations_calendar_unique_model_period_due ON public.obligations_calendar USING btree (company_id, model_code, COALESCE(period_key, ''::text), due_date) WHERE ((model_code IS NOT NULL) AND (status <> 'cancelled'::text));
CREATE INDEX orders_case_id_idx ON public.orders USING btree (case_id) WHERE (case_id IS NOT NULL);
CREATE INDEX orders_client_created_idx ON public.orders USING btree (client_id, created_at DESC);
CREATE INDEX orders_client_id_idx ON public.orders USING btree (client_id);
CREATE INDEX orders_company_idx ON public.orders USING btree (company_id) WHERE (company_id IS NOT NULL);
CREATE INDEX orders_holded_invoice_idx ON public.orders USING btree (holded_invoice_id) WHERE (holded_invoice_id IS NOT NULL);
CREATE INDEX orders_quote_id_idx ON public.orders USING btree (quote_id);
CREATE INDEX orders_source_idx ON public.orders USING btree (source);
CREATE UNIQUE INDEX orders_stripe_payment_id_idx ON public.orders USING btree (stripe_payment_id) WHERE (stripe_payment_id IS NOT NULL);
CREATE INDEX orders_tenant_id_idx ON public.orders USING btree (tenant_id) WHERE (tenant_id IS NOT NULL);
CREATE INDEX profile_companies_company_idx ON public.profile_companies USING btree (company_id);
CREATE INDEX profile_companies_profile_idx ON public.profile_companies USING btree (profile_id);
CREATE INDEX idx_profiles_has_monthly_plan ON public.profiles USING btree (has_monthly_plan) WHERE (has_monthly_plan = true);
CREATE INDEX profiles_checkout_readiness_idx ON public.profiles USING btree (profile_completed, billing_ready);
CREATE INDEX profiles_email_idx ON public.profiles USING btree (email);
CREATE INDEX profiles_onboarding_pending_idx ON public.profiles USING btree (created_at) WHERE (onboarding_completed_at IS NULL);
CREATE INDEX profiles_role_status_idx ON public.profiles USING btree (role, status, created_at DESC);
CREATE INDEX profiles_role_tenant_idx ON public.profiles USING btree (role, tenant_id) WHERE ((role = 'tenant_admin'::text) AND (tenant_id IS NOT NULL));
CREATE INDEX profiles_tenant_id_idx ON public.profiles USING btree (tenant_id) WHERE (tenant_id IS NOT NULL);
CREATE INDEX quotes_company_id_idx ON public.quotes USING btree (company_id);
CREATE INDEX quotes_tenant_id_idx ON public.quotes USING btree (tenant_id) WHERE (tenant_id IS NOT NULL);
CREATE INDEX review_requests_case_idx ON public.review_requests USING btree (case_id);
CREATE INDEX review_requests_client_idx ON public.review_requests USING btree (client_id);
CREATE UNIQUE INDEX review_requests_token_unique ON public.review_requests USING btree (token) WHERE (token IS NOT NULL);
CREATE INDEX reviews_client_idx ON public.reviews USING btree (client_id);
CREATE INDEX reviews_published_idx ON public.reviews USING btree (published, created_at DESC);
CREATE INDEX saas_leads_created_at_idx ON public.saas_leads USING btree (created_at DESC);
CREATE INDEX saas_leads_email_idx ON public.saas_leads USING btree (lower(email));
CREATE INDEX saas_leads_status_idx ON public.saas_leads USING btree (status);
CREATE INDEX idx_security_alerts_resolved ON public.security_alerts USING btree (resolved) WHERE (resolved = false);
CREATE INDEX idx_security_alerts_type ON public.security_alerts USING btree (alert_type, created_at DESC);
CREATE INDEX idx_prof_events_case_id ON public.service_profitability_events USING btree (case_id);
CREATE INDEX idx_prof_events_created_at ON public.service_profitability_events USING btree (created_at);
CREATE INDEX idx_prof_events_service_id ON public.service_profitability_events USING btree (service_id);
CREATE UNIQUE INDEX idx_prof_snapshots_case_unique ON public.service_profitability_snapshots USING btree (case_id, scope) WHERE ((scope = 'case'::text) AND (case_id IS NOT NULL));
CREATE INDEX idx_prof_snapshots_period ON public.service_profitability_snapshots USING btree (period);
CREATE INDEX idx_prof_snapshots_scope ON public.service_profitability_snapshots USING btree (scope);
CREATE INDEX idx_prof_snapshots_service_id ON public.service_profitability_snapshots USING btree (service_id);
CREATE UNIQUE INDEX idx_prof_snapshots_unique ON public.service_profitability_snapshots USING btree (service_id, period, scope) WHERE (scope = 'monthly'::text);
CREATE INDEX idx_sra_created_at ON public.service_readiness_assessments USING btree (created_at DESC);
CREATE INDEX idx_sra_service_slug ON public.service_readiness_assessments USING btree (service_slug);
CREATE INDEX idx_sra_user_id ON public.service_readiness_assessments USING btree (user_id);
CREATE INDEX stripe_invoice_company_attributions_company_idx ON public.stripe_invoice_company_attributions USING btree (company_id, status, created_at DESC);
CREATE INDEX stripe_invoice_company_attributions_customer_idx ON public.stripe_invoice_company_attributions USING btree (stripe_customer_id, status, created_at DESC);
CREATE UNIQUE INDEX stripe_invoice_company_attributions_one_active_idx ON public.stripe_invoice_company_attributions USING btree (tenant_id, stripe_invoice_id) WHERE (status = 'active'::text);
CREATE INDEX stripe_processed_events_processed_at_idx ON public.stripe_processed_events USING btree (processed_at);
CREATE UNIQUE INDEX subscription_checkout_claims_active_intent_uidx ON public.subscription_checkout_claims USING btree (user_id, company_id, intent_key) WHERE (state = ANY (ARRAY['claimed'::text, 'open'::text, 'manual_review'::text]));
CREATE INDEX subscription_checkout_claims_lease_idx ON public.subscription_checkout_claims USING btree (lease_expires_at) WHERE (state = 'claimed'::text);
CREATE UNIQUE INDEX subscription_checkout_claims_session_uidx ON public.subscription_checkout_claims USING btree (stripe_session_id) WHERE (stripe_session_id IS NOT NULL);
CREATE INDEX idx_entitlements_beneficiary_company_active ON public.subscription_entitlements USING btree (beneficiary_company_id, active, feature_key) WHERE (beneficiary_company_id IS NOT NULL);
CREATE INDEX idx_entitlements_checkout_session ON public.subscription_entitlements USING btree (checkout_session_id) WHERE (checkout_session_id IS NOT NULL);
CREATE INDEX idx_entitlements_client_active ON public.subscription_entitlements USING btree (client_id, feature_key) WHERE (active = true);
CREATE INDEX idx_entitlements_client_id ON public.subscription_entitlements USING btree (client_id);
CREATE INDEX idx_entitlements_primary_company_active ON public.subscription_entitlements USING btree (primary_company_id, active, feature_key) WHERE (primary_company_id IS NOT NULL);
CREATE INDEX idx_entitlements_subscription_id ON public.subscription_entitlements USING btree (subscription_id) WHERE (subscription_id IS NOT NULL);
CREATE UNIQUE INDEX subscription_entitlements_one_active_commercial_benefit ON public.subscription_entitlements USING btree (client_id, primary_company_id, beneficiary_company_id, feature_key, COALESCE(subscription_id, checkout_session_id)) WHERE ((active = true) AND (feature_key = ANY (ARRAY['included_entity'::text, 'discount_percent'::text, 'discount_amount'::text, 'free_months'::text])) AND (primary_company_id IS NOT NULL) AND (beneficiary_company_id IS NOT NULL) AND (COALESCE(subscription_id, checkout_session_id) IS NOT NULL));
CREATE INDEX subscription_trials_client_idx ON public.subscription_trials USING btree (client_id);
CREATE UNIQUE INDEX subscription_trials_client_plan_active_idx ON public.subscription_trials USING btree (client_id, plan_slug) WHERE ((company_id IS NULL) AND (status = ANY (ARRAY['trialing'::text, 'converted'::text])));
CREATE UNIQUE INDEX subscription_trials_company_plan_active_idx ON public.subscription_trials USING btree (company_id, plan_slug) WHERE (status = ANY (ARRAY['trialing'::text, 'converted'::text]));
CREATE INDEX subscription_trials_status_idx ON public.subscription_trials USING btree (status);
CREATE INDEX subscription_trials_stripe_sub_idx ON public.subscription_trials USING btree (stripe_subscription_id);
CREATE INDEX subscription_trials_trial_end_idx ON public.subscription_trials USING btree (trial_end);
CREATE INDEX subscriptions_company_id_idx ON public.subscriptions USING btree (company_id);
CREATE INDEX idx_support_tickets_category ON public.support_tickets USING btree (category);
CREATE INDEX idx_support_tickets_priority ON public.support_tickets USING btree (priority);
CREATE INDEX idx_support_tickets_status ON public.support_tickets USING btree (status);
CREATE INDEX idx_support_tickets_user_id ON public.support_tickets USING btree (user_id);
CREATE INDEX idx_training_orders_company_id ON public.training_orders USING btree (company_id);
CREATE INDEX idx_training_orders_status ON public.training_orders USING btree (status);
CREATE INDEX idx_training_orders_user_id ON public.training_orders USING btree (user_id);
CREATE INDEX idx_user_profiles_ext_email ON public.user_profiles_ext USING btree (email);
CREATE INDEX idx_user_profiles_ext_google_id ON public.user_profiles_ext USING btree (google_id);
CREATE INDEX idx_user_profiles_ext_holded_account_id ON public.user_profiles_ext USING btree (holded_account_id);
CREATE INDEX viability_assessments_client_email_idx ON public.viability_assessments USING btree (client_email);
CREATE INDEX viability_assessments_created_at_idx ON public.viability_assessments USING btree (created_at DESC);
CREATE INDEX viability_assessments_service_slug_idx ON public.viability_assessments USING btree (service_slug);
CREATE INDEX idx_wa_conv_case ON public.whatsapp_conversations USING btree (case_id);
CREATE INDEX idx_wa_conv_needs_rev ON public.whatsapp_conversations USING btree (needs_review) WHERE (needs_review = true);
CREATE INDEX idx_wa_conv_phone ON public.whatsapp_conversations USING btree (phone_number);
CREATE INDEX idx_whatsapp_conv_needs_review ON public.whatsapp_conversations USING btree (needs_review) WHERE (needs_review = true);
CREATE INDEX idx_whatsapp_conv_phone ON public.whatsapp_conversations USING btree (phone_number, created_at DESC);
CREATE INDEX whatsapp_conversations_reply_to_idx ON public.whatsapp_conversations USING btree (reply_to_message_id);
